_scripts/dockerRun.sh
cmd/govim/functions.go
cmd/govim/gopls_client.go
cmd/govim/main.go
cmd/govim/util.go
govim.go
testdriver/testdriver.go

Also fixed the UTF-16 position information

cmd/govim: call DidOpen and DidChange for buffers

---

cmd/govim/functions.go
cmd/govim/main.go
cmd/govim/main_test.go
govim.go
govim_test.go
testdriver/testdriver.go

Also do some renames in testdriver to remove potential for confusion in
what a Driver is.

govim: refactor to define concept of a Plugin

---

_scripts/runDockerRun.sh
cmd/govim/config/config.go
cmd/govim/functions.go
cmd/govim/testdata/format_on_save.txt
plugin/govim.vim

Also start the definition of a config package

cmd/govim: support for goimports code action

---

govim.go
govim_test.go
internal/plugin/plugin.go
plugin/govim.vim
testdata/call.txt
testdata/function.txt
testdriver/testdriver.go

This code was not properly tested and so the edge cases of the different
signatures possible within Vim was not exercised. Fix that.

govim: fix declaration of functions in Vim

---

Dockerfile
demos/go.mod
demos/hover.go

Also disable GUI support within Docker-based Vim

demos: initial commit

---

_scripts/dockerRun.sh
cmd/govim/functions.go
cmd/govim/main.go
cmd/govim/testdata/format_on_save.txt
cmd/govim/testdata/go_to_def.txt
cmd/govim/types/types.go
cmd/govim/util.go
go.mod
go.sum
govim.go
internal/plugin/plugin.go
testdriver/testdriver.go
tools.go

Also add a test for GOVIMGoToDef

all: tidy up and docs

---

cmd/govim/config/config.go
cmd/govim/functions.go
cmd/govim/main.go
cmd/govim/main_test.go
cmd/govim/testdatainstall/install_pathogen.txt
cmd/govim/testdatainstall/install_vim-plug.txt
cmd/govim/testdatainstall/install_vim8_packages.txt
cmd/govim/testdatainstall/install_vundle.txt
command.go
govim.go
internal/plugin/plugin.go
plugin/govim.vim
plugin/test_callback.txt
test

Also a bunch of tidy up including:
* automatically running events when cmd/govim loaded
* move function/command names to config

cmd/govim: fix install test scripts

---

cmd/govim/functions.go
cmd/govim/testdata/bad_complete.txt

cmd/govim: workaround a Vim and gopls bug in completions

---

.travis.yml

Following https://github.com/vim/vim/issues/4244

deps: upgrade minimum Vim requirement

---

.travis.yml
cmd/govim/main_test.go
event_queue.go
govim.go
plugin/govim.vim
testdriver/testdriver.go
viewport.go

govim: make schedule more useful and fix TestDriver

---

plugin/govim.vim

* try to improve system() calls to capture stderr
* do not force syntax on
* be chatty when installing govim and gopls
Fixes #149
Fixes #150

plugin: improve VimScript shim

---

cmd/govim/functions.go

Also fix logic error whereby we were always updating the quickfix list
regardless of whether there had been any updates from the server

cmd/govim: use setqflist instead of cgetfile

---

cmd/govim/functions.go
cmd/govim/main.go

Otherwise we will potentially end up with stale data in govim

cmd/govim: handle buffer delete event

---

cmd/govim/functions.go
command.go
const.go
internal/plugin/plugin.go
plugin/govim.vim
testdata/expr.txt
testdriver/testdriver.go

* Add <mods> support to commands
* Make vim sidecar not pretty-print JSON by default; add flag
* Add constant defs of switchbuf modes
* Add plugin convenience for Viewport

govim,cmd/govim: various bits

---

cmd/govim/config/config.go
cmd/govim/functions.go
cmd/govim/main.go
cmd/govim/main_test.go
ftplugin/go.vim
govim_test.go
minimal.vimrc
plugin/govim.vim
testdriver/test.vim
testdriver/testdriver.go

cmd/govim: restructure to use ftplugin

---

cmd/govim/ftplugin.go
cmd/govim/functions.go

Makes linking to these defaults easier

cmd/govim: move ftplugin callback into separate file

---

cmd/govim/internal/lsp/cmd/cmd.go
cmd/govim/internal/lsp/cmd/format.go
cmd/govim/internal/lsp/source/completion.go
cmd/govim/internal/lsp/source/completion_format.go
cmd/govim/internal/lsp/source/signature_help.go
cmd/govim/internal/lsp/source/util.go
cmd/govim/internal/lsp/testdata/foo/foo.go
cmd/govim/internal/lsp/testdata/format/bad_format.gofmt-d.golden.go
cmd/govim/internal/lsp/testdata/format/newline_format.gofmt-d.golden.go
cmd/govim/internal/lsp/tests/tests.go
go.mod
go.sum

* internal/lsp/source: refactor completion
* internal/lsp: handle shadowed variables in lexical completions
* internal/lsp: add the format command line

deps: golang.org/x/tools v0.0.0-20190428024724-550556f78a90

---

cmd/govim/internal/lsp/completion.go
cmd/govim/internal/lsp/source/completion.go
cmd/govim/internal/lsp/source/completion_format.go
cmd/govim/internal/lsp/source/completion_snippet.go
cmd/govim/internal/lsp/testdata/snippets/snippets.go
cmd/govim/internal/lsp/tests/tests.go
cmd/govim/internal/span/utf16.go
go.mod
go.sum

* internal/span: fix another off-by-one in ToUTF16Column
* internal/lsp: add struct literal field snippets

deps: golang.org/x/tools v0.0.0-20190429181656-7af746645d51

---

.gitattributes

Per https://github.com/github/linguist/issues/2206#issuecomment-339272910

github: mark cmd/govim/internal as generated to supprress GitHub diffs

---

.docker_env_file
_scripts/dockerRun.sh
_scripts/runDockerRun.sh

Had some random test flakes that looked attributable to GitHub rate
limits being exceeded

ci: switch to using GitHub tokens

---

_scripts/runDockerRun.sh

Per suggestion from Travis folks.
Fixes #216

ci: use --network host for docker run to fix network flake

---

_scripts/runDockerRun.sh

This reverts commit 1337a8624c2e24cc1914d1ecc95e2b4a5af181f7.

ci: revert use --network host for docker run to fix network flake

---

README.md

Fix broken link to minimal vimrc in README

---

cmd/govim/buffer_events.go
cmd/govim/quickfix.go
cmd/govim/types/types.go
cmd/govim/util.go

I'm amazed this hadn't reared its head before.

cmd/govim: fix shockingly bad buffer caching bug

---

go.mod
go.sum

See https://github.com/golang/go/issues/32527 for details

deps: use latest pty in order to allow working with Go tip

---

cmd/govim/format.go

Currently we can end up triggering an listener_add callback for every
format change in a buffer. This is incredibly inefficient because we
will always be applying such changes in a batch.
Instead, drop the listener, apply the changes, read the entire buffer
contents, fire didChange, then re-add the listener.

cmd/govim: improve efficiency of format changes

---

cmd/govim/config/config.go
cmd/govim/main.go
cmd/govim/rename.go
cmd/govim/testdata/rename.txt

cmd/govim: initial cut of rename

---

cmd/govim/main.go
cmd/govim/quickfix.go
cmd/govim/signs.go
cmd/govim/testdata/signs.txt
testsetup/testsetup.go

Moved branch due to CI issues, see #382

cmd/govim: add signs to quickfix entries (#284)

---

autoload/govim/config.vim
cmd/govim/config/config.go
cmd/govim/signs.go
cmd/govim/testdata/quickfix_config.txt
cmd/govim/testdata/signs.txt
cmd/govim/vimstate.go

cmd/govim: add QuickfixSignsDisable config

---

cmd/govim/testdata/gofmt.txt
cmd/govim/testdata/goimports.txt

cmd/govim: attempt to fix format-related flakes

---

testdriver/testdriver.go

This PR will update `errlogmatch` so that the search start offset for the next call is based on the last match instead of how the errlog looked at the last call.
It will also rename the flag `leavelast` to `peek` to reflect the new behavior.

testdriver: update errlogmatch logic

---

govim.go

This PR will add a random three char instance ID to each log line.
Feels like three letters "ought to be enough for anyone", and it would be fairly obvious if a collision occurred.
This is a fairly simple solution, and hopefully the extra chars won't confuse anyone. Also appended the ID after the timestamp, with an underscore as a separator. That way none of the regex's in the existing test scripts needed to change.
Closes #407

govim: add 3 char random instance id to logs

---

cmd/govim/gopls_client.go
cmd/govim/test_config.go
cmd/govim/testdata/show_message.txt

cmd/govim: show vim popup when MessageType is Error in ShowMessage 

---

cmd/govim/format.go

When calling CodeAction in FormatOnSave gopls might return other code actions except formating, for example quickfixes.
This change ignores all code actions except SourceOrganizeImports in format.go and the purpose is to avoid errors for now. Code actions might need another handling design when handling of suggested fixes is implemented.
Fixes #527

cmd/govim: only handle organizeImports in format CodeAction response

---

cmd/govim/internal/golang_org_x_tools/lsp/cmd/test/cmdtest.go
cmd/govim/internal/golang_org_x_tools/lsp/source/completion.go
cmd/govim/internal/golang_org_x_tools/lsp/source/options.go
cmd/govim/internal/golang_org_x_tools/lsp/testdata/casesensitive/casesensitive.go
cmd/govim/internal/golang_org_x_tools/lsp/tests/tests.go
go.mod
go.sum

* internal/lsp: provide option for case sensitive completion a8d5d342

deps: upgrade to gopls and x/tools a8d5d342

---

cmd/govim/internal/golang_org_x_tools/imports/fix.go
cmd/govim/internal/golang_org_x_tools/lsp/cache/pkg.go
cmd/govim/internal/golang_org_x_tools/lsp/cache/view.go
cmd/govim/internal/golang_org_x_tools/lsp/source/completion.go
cmd/govim/internal/golang_org_x_tools/lsp/source/completion_format.go
cmd/govim/internal/golang_org_x_tools/lsp/source/completion_literal.go
cmd/govim/internal/golang_org_x_tools/lsp/source/deep_completion.go
cmd/govim/internal/golang_org_x_tools/lsp/source/options.go
go.mod
go.sum

* internal/imports: set import names on completion candidates 689d0f08
* internal/lsp: add config flag to hide debugging output ea203083
* internal/lsp/source: attach Package to completions when available 81855518

deps: upgrade to gopls and x/tools 689d0f08e67a

---

_scripts/revendorToolsInternal.sh

The version of bash shipped with macOS doesn't support shopt globstar,
the syntax of sed is a little bit different between Linux and macOS and
rsync --chmod acts different.
This change adds support for running revendorToolsInternal.sh on macOS
and is intended mostly for the use case where you would like to update
gopls version during development. The rsync chmod'ing won't behave
identical to the Linux version, but close enough for most use cases.

scripts: Add darwin support to revendorToolsInternal

---

cmd/govim/vimstate.go

Now that https://go-review.googlesource.com/c/tools/+/206148 has landed
we can trigger a call to gopls to refetch configuration whenever the
user calls govim#config#Set() from Vim.
We will add proper tests in a future PR but from an intial test with
tweaking the staticcheck config on/off it doesn't look like gopls is
retriggering sending of diagnostics or actually turning on staticcheck
in the edge off -> on.

cmd/govim: trigger gopls.DidConfigurationChange on config change

---

autoload/govim/config.vim
cmd/govim/config/config.go
cmd/govim/gopls_client.go
cmd/govim/internal/vimconfig/vimconfig.go
cmd/govim/testdata/mod/rubbish.com_useless_v1.0.0.txt
cmd/govim/testdata/scenario_goimports_local/default_config.json
cmd/govim/testdata/scenario_goimports_local/existing_import.txt
cmd/govim/testdata/scenario_goimports_local/new_import.txt

cmd/govim: add support for goimports -local equivalent config

---

cmd/govim/buffer_events.go
cmd/govim/main.go

cmd/govim: implement LSP DidSave

---

cmd/govim/main_test.go

For validating changes to gopls, it would be helpful to be able to run
the govim integration tests against a specific copy of the gopls binary.
Currently, the scenario tests run against a freshly built pinned version
of gopls.
A -gopls flag is added to allow specifying a path to a pre-existing copy
of gopls, for use in these scenario tests.

tests: add a -gopls flag for scenario tests in cmd/govim

---

cmd/govim/quickfix.go
cmd/govim/testdata/scenario_default/quickfix_config.txt

See commit message for details.

cmd/govim: fix GOVIMQuickfixDiagnostics command

---

cmd/govim/signs.go

Currently govim defines the different sign types used at startup,
with hard coded sign (">>").
This adds a check before each sign definition that skips definition
if a sign with that name is already defined. It allows the user to
override sign types used by govim in their vimrc and that way use
custom signs.
e.g. to change sign to "!!" instead for errors:
call sign_define("GOVIMSignErr",{"text":"!!","texthl":"GOVIMSignErr"})
Fixes #633

cmd/govim: allow user defined signs

---

cmd/govim/buffer_events.go

We currently blindly increase buffer version when vim triggers
BufReadPost or BufNewFile (and a didOpen or didChange request to
gopls). Unloading and loading a buffer that is open also triggers
a BufReadPost, and if the content didn't change we shouldn't
increase version.
This change also skip redefining highlights if the version is
indeed increased since the last known diagnostics could have
changed.
Updates #655

cmd/govim: Do not increase version if buffer content didn't change

---

.github/FUNDING.yml

@leitzler has been a huge contributor to the project. Thank you!

github: add @leitzler to funding.yml

---

go.mod
go.sum

Remove unnecessary indirect module requirements

ci: tidy up go.{mod,sum}

---

testdriver/testdriver.go

Also properly handle git-ignored files instead of maintaining a list of
our own in code.

testdriver: do not try to copy symlink files

---

cmd/govim/config/config.go
cmd/govim/format.go
cmd/govim/main.go
cmd/govim/testdata/scenario_default/format_on_save_default.txt
cmd/govim/testdata/scenario_default/goimports.txt

cmd/govim: split config.FormatOnSaveGoImports into component parts

---

cmd/govim/internal/golang_org_x_tools/jsonrpc2/jsonrpc2.go
cmd/govim/internal/golang_org_x_tools/lsp/cache/mod.go
cmd/govim/internal/golang_org_x_tools/lsp/cmd/serve.go
cmd/govim/internal/golang_org_x_tools/lsp/cmd/test/cmdtest.go
cmd/govim/internal/golang_org_x_tools/lsp/command.go
cmd/govim/internal/golang_org_x_tools/lsp/fake/edit.go
cmd/govim/internal/golang_org_x_tools/lsp/lsprpc/lsprpc.go
cmd/govim/internal/golang_org_x_tools/lsp/mod/code_lens.go
cmd/govim/internal/golang_org_x_tools/lsp/regtest/env.go
cmd/govim/internal/golang_org_x_tools/lsp/server.go
cmd/govim/internal/golang_org_x_tools/lsp/source/options.go
cmd/govim/internal/golang_org_x_tools/lsp/source/view.go
cmd/govim/internal/golang_org_x_tools/lsp/testdata/lsp/summary.txt.golden
cmd/govim/internal/golang_org_x_tools/lsp/testdata/missingdep/summary.txt.golden
cmd/govim/internal/golang_org_x_tools/lsp/testdata/missingtwodep/summary.txt.golden
cmd/govim/internal/golang_org_x_tools/lsp/testdata/unused/summary.txt.golden
cmd/govim/internal/golang_org_x_tools/lsp/testdata/upgradedep/modules/example.com/extramodule@v1.0.0/pkg/x.go
cmd/govim/internal/golang_org_x_tools/lsp/testdata/upgradedep/modules/example.com/extramodule@v1.1.0/pkg/x.go
cmd/govim/internal/golang_org_x_tools/lsp/testdata/upgradedep/summary.txt.golden
cmd/govim/internal/golang_org_x_tools/lsp/tests/tests.go
cmd/govim/internal/golang_org_x_tools/lsp/tests/util.go
go.mod
go.sum

* internal/jsonrpc2: fix races in cancellation 88be0131
* internal/lsp/lsprpc: add an LSP forwarder and regtest environment 0fd2d649
* internal/lsp: add codelens for go.mod dependency upgrades 98b3097d

deps: upgrade x/tools and gopls to 88be0131

---

go.mod
go.sum

See https://github.com/creack/pty/issues/96 for details of the original
issue.

deps: upgrade github.com/creack/pty to v1.1.10 to fix Go1.15 issue

---

cmd/govim/internal/golang_org_x_tools/lsp/command.go
go.mod
go.sum

* internal/lsp: use ForTest package name when running test command 368bee87

deps: update x/tools and gopls to 368bee87

---

README.md

Noticed these while going through the docs again.

README: minor language tweaks

---

cmd/govim/main.go

The file watcher didn't work when opening a module located in the temp
directory on macOS (e.g. "cd $(mktemp -d)").
This happend since vim returned the real path, e.g.
"/private/var/folders/..." when calling getcwd(-1), but as exec.Command
works on macOS it returned the returned the symlinked path, e.g.
"/var/folders/...".
We now apply the same work around as x/tools where the working directory
is appended as $PWD before calling exec.Command so it actually use the
working directory supplied.
Fixes #1035

cmd/govim: append working dir as PWD when calling go env GOMOD

---

autoload/govim/config.vim
cmd/govim/config/config.go
cmd/govim/config/gen_applygen.go
cmd/govim/gopls_client.go
cmd/govim/internal/vimconfig/vimconfig.go
cmd/govim/testdata/scenario_workspacemodule/user_config.json
cmd/govim/testdata/scenario_workspacemodule/workspace_module.txt

ExperimentalWorkspaceModule opts a user into the experimental gopls
support for multi-module workspaces
Fixes #1049

cmd/govim: add ExperimentalWorkspaceModule config option

---

cmd/govim/gopls_client.go
cmd/govim/internal/golang_org_x_tools/lsp/source/api_json.go
cmd/govim/internal/golang_org_x_tools/lsp/source/identifier.go
cmd/govim/internal/golang_org_x_tools/lsp/source/options.go
go.mod
go.sum

* internal/lsp: enable semantic tokens by default 5ab822f6
* internal/lsp: findIdentifier always return an error eb0b8a15

deps: update x/tools & gopls to 5ab822f6

---

cmd/govim/internal/fswatcher/os_others.go

Events from fsnotify might hold several "file operations" per event as
operation is a bit mask. It hasn't been observed that Linux ever do, but
it has been seen when running Darwin. Since govim doesn't use fsnotify
in darwin (we use fsevents), we haven't seen this fail in our tests.
This change checks operation bit masks so that combined operations
aren't lost.

cmd/govim: handle multi-op fsevents

---

_scripts/Dockerfile.gvim
_scripts/Dockerfile.vim
_scripts/publishDockerImages.sh
_scripts/rebuildDockerImages.sh

This ensures that we don't expose build args as part of the resulting
image.

_scripts: build docker images using --secret

---

channel_cmds.go

govim: fix bug in passing of variadic args

---

testdata/ex.txt

Not sure how this didn't get caught in #1200, but make this test more robust.

tests: make ex test more robust

---

cmd/govim/parent.go

cmd/govim: fix bad error capture

---

cmd/govim/code_action.go
cmd/govim/internal/golang_org_x_tools/analysisinternal/analysis.go
cmd/govim/internal/golang_org_x_tools_gopls/analysis/simplifyrange/simplifyrange.go
cmd/govim/internal/golang_org_x_tools_gopls/protocol/enums.go
cmd/govim/internal/golang_org_x_tools_gopls/settings/analysis.go
cmd/govim/internal/golang_org_x_tools_gopls/settings/codeactionkind.go
cmd/govim/internal/golang_org_x_tools_gopls/settings/default.go
cmd/govim/internal/golang_org_x_tools_gopls/settings/settings.go
go.mod
go.sum

deps: update x/tools and gopls to 850c7c3070cd
