govim/govim

testdata/function.txt, testdriver/testdriver.go
Allows stronger assertions for when commands should not fail.
=> testdriver: add -bang flag to signal command will fail

_scripts/dockerRun.sh
We don't need it to be environment-variable driven for now
=> _scripts: fix check for formatted go code

channel_cmds.go, cmd/govim/functions.go, cmd/govim/gopls_client.go, cmd/govim/main.go, cmd/govim/main_test.go, cmd/govim/util.go, command.go, govim.go, govim_test.go, internal/plugin/plugin.go, internal/queue/queue.go, plugin/govim.vim, testdriver/testdriver.go, userq.go, viewport.go
Some calls from govim to Vim will result in events. If such a call
happens in a function/command callback, then we will deadlock because
the events will not be able to "fire".
Instead we split out a separate event queue. This allows calls made from
govim to Vim to result in events and for that event queue to be flushed
before we return to the caller.
=> govim: refactor to have an explicit event queue

cmd/govim/functions.go
i.e. no valid completion is possible because, for example, the code does
not sufficiently type check
=> cmd/govim: add test for when completion "fails"

plugin/govim.vim, testdriver/test.vim
test.vim will continue to represent the minimal .vimrc required to use
govim
=> govim: move base config from govim.vim to test.vim

README.md, minimal.vimrc
* Also include linke to https://github.com/myitcv/govim/wiki/vimrc-tips
* Fix broken ttymouse default
=> README: make pointer to minimal.vimrc more explicit

.github/ISSUE_TEMPLATE
Very often useful messages will be shown by :messages in Vim. But it's
easy to miss such messages. Request the output from that command in the
template in order to prompt the user to consider that output first.
Then also ask for interesting bits from the log files, locations given
by :messages.
Add note of caution that logfiles include file contents.
=> issues: request :messages from Vim and log file hint as part of tmpl

cmd/govim/util.go
Autocmds like BufReadCmd don't reliably give us <afile> as the filename.
Instead we can use <abuf> and resolve via bufname
=> cmd/govim: explicitly use bufname instead of <afile>

cmd/govim/internal/lsp/cache/check.go, cmd/govim/internal/lsp/cache/parse.go, cmd/govim/internal/lsp/source/completion.go, cmd/govim/internal/lsp/testdata/badstmt/badstmt.go, cmd/govim/internal/lsp/testdata/bar/bar.go.in, cmd/govim/internal/lsp/testdata/basiclit/basiclit.go, cmd/govim/internal/lsp/testdata/baz/baz.go.in, cmd/govim/internal/lsp/testdata/comments/comments.go, cmd/govim/internal/lsp/testdata/stringlit/stringlit.go.in, cmd/govim/internal/lsp/tests/tests.go, go.mod, go.sum
To pick up:
* internal/lsp: handle completion after defer, go statements
* internal/lsp: suppress more completions in comments and literals
=> deps: update to golang.org/x/tools v0.0.0-20190425001055-9e44c1c40307

cmd/govim/internal/lsp/cache/check.go, cmd/govim/internal/lsp/cache/file.go, cmd/govim/internal/lsp/cache/pkg.go, cmd/govim/internal/lsp/snippet/snippet_builder.go, cmd/govim/internal/lsp/source/diagnostics.go, cmd/govim/internal/span/utf16.go, go.mod, go.sum
* internal/lsp: fix utf16 conversion for end of file cursor
* internal/lsp: extensive utf16 tests
* internal/lsp: handle error from runAnalyses
* internal/lsp: fix stuck diagnostic messages
* internal/lsp: return errors when we can't find a package
* internal/lsp: introduce snippet builder object
Fixes #98
=> deps: golang.org/x/tools v0.0.0-20190425221449-0c752f569a3e

cmd/govim/functions.go, cmd/govim/gopls_server.go, cmd/govim/main.go, cmd/govim/main_test.go, cmd/govim/testdata/complete_watched.txt, cmd/govim/types/types.go, cmd/govim/util.go, cmd/govim/watcher.go, go.mod, go.sum
For now use textDocument/didOpen and textDocument/didChange to deal with
generated files changing, whilst we await a proper implementation in
gopls via golang/go#31553.
=> cmd/govim: temporary implementation of file watching

plugin/govim.vim
It doesn't seem worth a best-efforts approach to supporting old Vim
versions. We can't make any guarantees about user experience... which is
a bad start.
=> cmd/govim: enforce the minimum Vim version requirement

cmd/govim/testdata/format_on_save_gofmt.txt, cmd/govim/testdata/format_on_save_goimports.txt, cmd/govim/testdata/format_on_save_none.txt, cmd/govim/util.go
Our method of getting the entire buffer from Vim was failing to add a
trailing (end of file) newline (\n). Hence we were passing the file
contents minus the trailing \n to gopls. Which results in a bug in calls
to Formatting/CodeAction, but is almost certainly also invalid.
You have to go out of your way to avoid writing a trailing \n in Vim,
and for .go files it's almost certainly the case that the user wants to
write one.
We can revisit this more precisely if there is a pressing case for _not_
having a trailing \n.
=> cmd/govim: ensure that we correctly add a newline to end of file

cmd/govim/testdatainstall/install_pathogen.txt
Appears to be a bit flakey; and we can depend directly on GitHub
instead.
=> cmd/govim: remove long test dependency on tpo.pe

cmd/govim/testdata/complete_watched.txt
It's possible that our processing of the test script is so fast that we
"beat" the watcher handling, and hence gopls has not seen the "new" file
as a result of the copy.
Add in a generous sleep for now to see that this fixes the flake.
=> cmd/govim: fix flake in cmd/govim/testdata/complete_watched.txt

.travis.yml, Dockerfile.base, Dockerfile.nvim, Dockerfile.user, Dockerfile.vim, _scripts/buildGovimImage.sh, _scripts/rebuildDockerImages.sh
This adds a separate Docker image with Neovim for running the govim tests on CI, as suggested in https://github.com/myitcv/govim/pull/186#issuecomment-488624860.
I decided to split out the `Dockerfile` into a `Dockerfile.vim` and `Dockerfile.nvim` (both building atop a `Dockerfile.base` layer with Go/vbash) rather than build both in the same image; this feels cleaner to me and avoids having image tags like `myitcv/govim:go1.12.4_vim_v8.1.1158_nvim_v0.3.5_v1`, but I don't feel strongly about this approach. It may make sense to move the Docker images into a subdirectory.
I've been able to test this locally using, e.g.  `GO_VERSION=go1.12.4 VIM_VERSION=v8.1.1158 NEOVIM_VERSIONS=v0.3.4,v0.3.5 _scripts/rebuildDockerImages.sh` - it builds the Vim and Neovim images separately.
=> ci: add Neovim Docker support

cmd/govim/main_test.go, cmd/govim/testdata/mapping_defaults_go_to_def.txt, ftplugin/go.vim
Following
https://github.com/vim/vim/commit/bb8476be871811e40ddc88c598d9e553aba7fb79
we have the ability to call test_setmouse to simulate mouse position.
This allows us to then add coverage to the default mappings for
GOVIMGoToDef and GOVIMGoToPrevDef.
Fix a bug in the default mappings that became clear with these tests.
=> cmd/govim: use test_setmouse in test for default go-to-def mappings

cmd/govim/config/config.go, cmd/govim/config/minimal.vimrc, cmd/govim/format.go, cmd/govim/main.go, cmd/govim/quickfix.go, plugin/govim.vim
* Provide an option to disable auto-population of the quickfix window
from gopls diagnotics
* Provide CommandQuickfixDiagnostics to manually trigger the population
of the quickfix window with diagnostics
* Make quickfix population from diagnostics best-efforts, i.e. skip on
any errors (like invalid positions)
* Move some user-level settings out of the plugin shim into
minimal.vimrc
* Whilst we are at it, fix a small bug where we were not calling
undojoin prior to any formatting/goimports fixes
=> cmd/govim: refine quickfix population

cmd/govim/complete.go, cmd/govim/testdata/complete.txt
https://go-review.googlesource.com/c/tools/+/176958 changed the
TextEdits returned from gopls to not be the trimmed version of the
label. This meant that we were effectively appending the entire
completion text after the prefix.
This wasn't caught in the completion tests because there we were
attempting a "naked" completion with no prefix.
Fix by fixing the test (which confirmed the bug) then fixing the results
returned from gopls.
Seemingly, a list of completion items from gopls can specify a start
position per item. This does not appear to be supported by Vim (see
:help complete-functions)
=> cmd/govim: fix completion

testdriver/testdriver.go
TestScripts/scripts/condition_vim was failing for me locally, as
Homebrew-installed vim prints out `macOS version` on the second line,
where we'd expect "Included patches"
=> Handle patch versions being printed on different lines

channel_cmds.go, govim.go, testdriver/testdriver.go
Seems more correct and useful.
=> govim: change DoProto signature to take func that returns error

channel_cmds.go, cmd/govim/gopls_client.go, cmd/govim/main.go, govim.go, plugin/govim.vim, testdriver/testdriver.go
Because Vim and gopls are both sources of events as far as govim is
concerned, we effectively have a race when it comes to shutdown. Vim
will always be the one initiating the shutdown, but that notice can
happen at exactly the same time as receiving a message from gopls that
requires us to do something in Vim.
Hence shutdown is initiated by Vim by closing the channel. This allows
the read loop in govim to exit cleanly.
But at this point writes to the connection (off the back of events from
gopls for example) will fail.
Therefore, we define that any error whilst attempting to write to the
connection is indicative of the fact that we (govim) are shutting down.
When we detect we are shutting down, we panic with a known error. This
allows us to cleanly and quickly unwind in a well defined …
=> govim: initial definition of shutdown sequence

cmd/govim/config/config.go, ftplugin/go.vim
Helps the user distinguish between end-user functions and internal
functions that are only exposed for use by govim.
These internal functions could well at a later date be flipped to be
further obscured as closures of the plugin/govim.vim script (and hence
not even named).
=> cmd/govim: mark some functions as internal

_scripts/dockerRun.sh
For ad hoc testing within a docker container, these are not essential.
Particularly of GOPROXY is now set.
=> ci: make GH_USER and GH_TOKEN optional

cmd/govim/main.go
Means that by default incremental updates will be off.
=> cmd/govim: change default of GOVIM_DISABLE_INCREMENTALSYNC to true

cmd/govim/format.go
Use "try | silent undojoin | catch | endtry" instead of a plain
undojoin, in case the command immediately prior to save was an undo.
=> cmd/govim: allow undo before format-on-save

cmd/govim/gopls_client.go
The window/logMessage method is exactly that; a means for the server to
log a message with the client. It is distinct from window/showMessage
(not yet used in gopls).
We were, therefore, incorrectly showing messages that were being logged
by the LSP server.
=> cmd/govim: do not show LogMessage arguments

cmd/govim/buffer_events.go, cmd/govim/format.go, cmd/govim/main.go, plugin/govim.vim
This way, we always make changes to buffers in Vim/VimScript. This
avoids the scenario described in
https://github.com/vim/vim/issues/4438#issuecomment-496448888.
=> cmd/govim: fix and re-enable deltas; apply format updates in batches

cmd/govim/main.go, plugin/govim.vim, testsetup/testsetup.go
This means that doing quick repros of problems etc doesn't result in
lots of separate vim channel/govim log files for different Vim sessions.
This way, be setting GOVIM_LOGFILE_TMPL=%v, you then have a stable file
that is logged to, and hence can tail etc without needing to change the
file you are tailing.
=> cmd/govim: accept logfile template via GOVIM_LOGFILE_TMPL

cmd/govim/format.go, govim.go, plugin/govim.vim, viewport.go
Vim is not currently in a position to be able to accurately push
viewport changes to govim. Hence, we might as well drop this code, not
least because it clutters the log messages having the viewport changes
being pushed the whole time. But also because we don't have anything in
govim that relies on knowing when the viewport changes (that is #24).
This should also make adding the Neovim support easier.
=> govim: remove viewport subscription code

cmd/govim/gopls_client.go, cmd/govim/main.go, cmd/govim/quickfix.go, cmd/govim/testdata/quickfix.txt
The current implementation of populating the quickfix window relied on the
CursorHold/CursorHoldI event firing _after_ the diagnostics for a file
had been delivered. However, this is obviously completely wrong; there
is nothing that guarantees this condition will always hold.
Instead, simply use the event of new diagnostics being delivered from
gopls to update the quickfix window.
Fixes #255
=> cmd/govim: fix quickfix implementation

cmd/govim/main_test.go, testsetup/testsetup.go
This makes it much easier to turn out govim logging to stderr when
debugging issues.
=> cmd/govim: add GOVIM_TESTSCRIPT_STDERR to quickly turn on stderr output

autoload/govim/config.vim, channel_cmds.go, cmd/govim/config/config.go, cmd/govim/format.go, cmd/govim/functions.go, cmd/govim/gopls_client.go, cmd/govim/main.go, cmd/govim/main_test.go, cmd/govim/testdata/format_on_save_none.txt, cmd/govim/testdata/gofmt.txt, cmd/govim/testdata/goimports.txt, event_queue.go, govim.go, govim_test.go, plugin/govim.vim, testdriver/testdriver.go
This moves us from the approach of delacring global variables in one's
.vimrc:
let g:govim_quickfix_auto_diagnotics_disable=1
to calling a config function:
call govim#config#Set("quickfix_auto_diagnotics_disable", 1)
The benefits here being:
* better validation of config setting; this function can error if you try to set
an invalid key/value
* consistent approach to setting config at startup (.vimrc) or runtime
* more efficient config processing by govim
As part of these changes we also make our load, init and shutdown events
from a Govim instance for explicit, and therefore their handling in
testdriver more robust.
Closes #264
=> cmd/govim: switch to using config functions

cmd/govim/main.go, cmd/govim/testdata/complete.txt
Noting however https://github.com/myitcv/govim/issues/266 which is a
known issue. Re-enabling on the basis it's probably better to get more
exposure for this feature in the short term, particularly when there is
a workaround for people who use auto-pairs.
=> cmd/govim: re-enable incremental updates by default

cmd/govim/main_test.go, cmd/govim/testdata/complete.txt, cmd/govim/testdata/complete_watched.txt, cmd/govim/testdata/go_to_def_useopen.txt, cmd/govim/testdata/quickfix.txt, govim_test.go, testdata/bad_function.txt, testdata/function.txt, testdriver/testdriver.go
Also add goplslogcount in order to easily make assertions against the
number of errors (for example) in a test run.
=> testdriver: make errlogmatch more useful

cmd/govim/format.go, cmd/govim/main_test.go, cmd/govim/testdata/gofmt.txt, cmd/govim/testdata/goimports.txt
Syntax errors in a file mean that a call to any of the gopls methods
that format the code will fail. This is confirmed by those methods
returning errors.
Currently we return that error to Vim, meaning the error is thrown. Not
only that, but, if the format function is called as part of
format-on-save, then the save is aborted.
Per #274, this is not ideal.
Instead, we choose Option 2 in #274 for now:
* allow the save
* do not echo/throw any error
* rely on the user spotting the syntax error in the quickfix window
We might follow this up with a further PR that automatically shows the
quickfix window if there are any errors in it, but not for now.
Fixes #274
=> cmd/govim: better model for handling syntax errors

cmd/govim/main_test.go, cmd/govim/testdata/bad_complete.txt, cmd/govim/testdata/command.txt, cmd/govim/testdata/complete.txt, cmd/govim/testdata/complete_watched.txt, cmd/govim/testdata/format_on_save_none.txt, cmd/govim/testdata/function.txt, cmd/govim/testdata/function_hover.txt, cmd/govim/testdata/go_to_def_newtab.txt, cmd/govim/testdata/go_to_def_same_file.txt, cmd/govim/testdata/go_to_def_split.txt, cmd/govim/testdata/go_to_def_useopen.txt, cmd/govim/testdata/go_to_def_usetab.txt, cmd/govim/testdata/go_to_def_vsplit.txt, cmd/govim/testdata/gofmt.txt, cmd/govim/testdata/goimports.txt, cmd/govim/testdata/mapping_defaults_go_to_def.txt, cmd/govim/testdata/quickfix.txt, testdriver/testdriver.go
Drop goplslogcount in favour of the more explicit errlogmatch, which has
now gained a -count flag.
=> testdriver: improve errlogmatch

cmd/govim/functions.go, cmd/govim/gopls_client.go, cmd/govim/main.go, cmd/govim/quickfix.go
This helps to throttle the number of changes we try to push through to
the quickfix window.
However, https://github.com/golang/go/issues/32443 remains an issue in
as much as incomplete diagnostics are sent to the client. i.e. we can't
be sure to receive the most recent diagnostics for the file which we are
editing (and in which we know, for example, we are making errors).
=> cmd/govim: de-dupe PublishDiagnostics notifications from gopls

cmd/govim/main_test.go, govim_test.go
Fixes #309, caused by overriding td.Log, blatting the output of errLog. This caused tests that used errlogmatch to fail, as there was no output to match on 🙂
=> cmd/govim: fix test failures when -govimLog is set

cmd/govim/functions.go
When a call to GOVIMReferences is made, it effectively puts the quick
fix window in a mode where it shows references, not diagnostics. We were
missing a check at the inflection point of "user is busy" for which mode
we were in, and hence in some situations we would override the list of
references with diagnostics (because errors had been introduced since
the call to GOVIMReferences)
=> cmd/govim: prevent diagnostics overwriting references

cmd/govim/complete.go
We were only displaying the Detail of a completion item, which is, for
example, the function signature. Instead, we display the label first,
then use the 'menu' option in Vim to display the detail.
Filed #339 to track adding a test for this.
=> cmd/govim: fix completion menu items

cmd/govim/main.go
This is unnecessary, and in future changes the ambiguity becomes
confusing. vimstate should never be accessed from *govimplugin, so the
embedding made that more confusing.
The field only exists in order that we can bootstrap correctly and
reference the methods defined on vimstate during function, command and
autocommand registration.
=> cmd/govim: do not embed vimstate in govimplugin

cmd/govim/internal/lsp/hover.go, go.mod, go.sum
* internal/lsp: remove the unused function 'markupContent'.
* internal/lsp: fix test failure introduced in CL 185058
=> deps: x/tools and gopls dd7c7173f160

cmd/govim/references.go, cmd/govim/testdata/references.txt
We then show other references in the file containing the definition
next, ordered by offset, then we lexically sort by file name and
offsets.
Fixes #327
=> cmd/govim: always show definition in GOVIMReferences first

cmd/govim/vimstate.go, plugin/govim.vim
Currently we define s:batchCall to take a variadic number of arguments.
This is unnecessary because it can take a single argument, a list. With
the signature being variadic, it also means we're likely to hit some
sort of Vim limit on the number of arguments that can be parsed.
This change changes the signature of that function to take a list,
thereby sidestepping all of these issues.
=> cmd/govim: fix bug for large batches

cmd/govim/hover.go
Returning empty string ensures that we show nothing. Returning nil means
we ultimately return null in JSON terms, which gets displayed as v:null
=> cmd/govim: fix hover when nothing to show

autoload/govim/config.vim, cmd/govim/config/config.go, cmd/govim/hover.go, cmd/govim/vimstate.go
Whilst we try to establish the best defaults for popup windows in
various contexts (#360), let's provide experimental config options to
allow users to help with this experiment.
For example, to set the options for mouse-trigger hover popups, add the
following to your .vimrc:
call govim#config#Set("ExperimentalMouseTriggeredHoverPopupOptions", {
\ "mousemoved": "any",
\ "pos": "botleft",
\ "line": -1,
\ "col": 0,
\ "moved": "any",
\ "border": [],
\ "wrap": v:false,
\ "close": "click",
\ "padding": [0, 1, 0, 1],
\})
See the go doc for github.com/myitcv/govim/cmd/govim/config for more
details on what config options can be set.
See :help popup_create-arguments for details of the various options that
can be set for ExperimentalMouseTriggeredHoverPopupOptions and …
=> cmd/govim: provide an experiment config option for popup options

cmd/govim/hover.go
We were not copying the may of user options when using it; instead we
were modifying the config in place.
=> cmd/govim: fix bug in use of user provided hover popup options

cmd/govim/hover.go
Left and right padding makes things look a little more comfortable (and
matches the behaviour of the omnifunc menu).
This change got missed in c79efa9a1bb9fbf1276d93b8702beadfb315de96.
=> cmd/govim: add padding to default hover popup window

cmd/govim/hover.go
We were incorrectly using window numbers instead of IDs for placement of
mouse-trigger and cursor-triggered hover popups. Fix that.
=> cmd/govim: use winid instead of winnr for hover placement

cmd/govim/quickfix.go, cmd/govim/testdata/quickfix.txt
Currently we only sort by filename, which means we are sensitive to the
order of results returned by gopls. Instead, fully sort by (filename,
line, col) to give properly order quickfix entries
=> cmd/govim: fully sort quickfix entries

cmd/govim/buffer_events.go, cmd/govim/config/config.go, cmd/govim/main.go, cmd/govim/main_test.go, cmd/govim/test_config.go, cmd/govim/vimstate.go, testsetup/testsetup.go
When testing cmd/govim we define certain functions, commands and
autocommands that are only required for testing purposes. Tidy these
into a separate file and use a nasty/nifty hack to only load these when
running tests.
=> cmd/govim: tidy up test definitions

cmd/govim/format.go, cmd/govim/test_config.go, cmd/govim/testdata/batch.txt, cmd/govim/vimstate.go, plugin/govim.vim
The previous implementation of the cmd/govim Batch "API" was a rough
first cut. This makes the implementation more robust and adds tests.
=> cmd/govim: replace batching implementation with something more robust

cmd/govim/config/config.go, cmd/govim/main.go, cmd/govim/stringfns.go, cmd/govim/testdata/stringfn.txt
```
GOVIMStringFns is a command that replaces buffer text with the result of
applying a sequence of transformation functions. With no range, the
current line is used as input. That is to say the current line is used
as the argument to the sequence of transformation functions.  Visual
selections can also be used to specify the range, however the command
has no meaning for visual blocks.
The command takes one or more arguments: the sequence of transformation
functions to apply. Each argument is a path to a transformation
function, e.g. strconv.Quote
Here is an example of applying multiple transformations to a visual
selection:
:'<,'>GOVIMStringFn crypto/sha256.Sum256 encoding/hex.EncodeToString
The goal with this command is to expose standard library functions to
help manipulate text. …
```
=> cmd/govim: initial cut of GOVIMStringFn command

cmd/govim/testdata/gofmt_eof.txt, cmd/govim/textedit.go
Also add a simple test for now to cover this. We should, per the comment
in the testscript, add a suite of tests to properly cover
[]protocol.TextEdit changes in various scenarios.
=> cmd/govim: fix bug handling edits at end of files

_scripts/runDockerRun.sh
Go doesn't require the env var GOPATH to be set since 1.8, `go env GOPATH` will however report the correct one even if it isn't set.
=> scripts: fix GOPATH in runDockerRun.sh

_scripts/runDockerRun.sh
The mod cache needs to be filled before using it as proxy since the GOPROXY can't be configured with fallback pre Go 1.13.
This PR will fill it before mounting it into the container.
Closes #404
=> prepopulate mod cache before using it as proxy

channel_cmds.go, event_queue.go, govim.go, internal/plugin/plugin.go
Currently we muddle up tomb.ErrDying errors with govim.ErrShuttingDown.
We only need one of these to indicate that govim is shutting down, and
it should be the latter; the former is an implementation detail.
As part of this tidy up, we also fix a bug in internal/plugin where we
were incorrectly wrapping as an ErrDriver an error caused by govim
shutting down. Given the simplification to now only use
govim.ErrShuttingDown to indicate the mode/event, we simply check we
aren't shutting down before otherwise creating a wrapped error.
Fixes #406
=> internal/plugin: tidy up shutdown errors

cmd/govim/config/minimal.vimrc
The out-of-the-box experience should be that the sign column is visible,
so as to prevent the dance of it (the sign column)
appearing/disappearing as errors come and go.
=> cmd/govim: add signcolumn=yes to minimal vimrc

cmd/govim/testdata/hover.txt, cmd/govim/testdata/mapping_defaults_go_to_def.txt
In 0404c34fe3a519a751240a40088e2c0f73f2a2fa I incorrectly attributed
test failures in cmd/govim/testdata/hover.txt and
cmd/govim/testdata/mapping_defaults_go_to_def.txt to flakes. These were
genuine failures. The change in that commit means that the signcolumn
will always be visible.
test_setmouse takes a _screen_ position. Therefore, turning on the
signcolumn meant that the screen position for positions in a buffer
shifted.
This kind of worked by accident before; we now use screenpos() to more
precisely set the mouse position.
Fixes #415
Fixes #416
=> cmd/govim fix test failures for scripts that use test_setmouse

cmd/govim/hover.go
Following an extremely unscientific poll on Slack, and as part of the
continuing experiment to establish the best out-of-the-box defaults, we
now place hover popups above-and-to-the-right of the cursor.
The main reasons for this change are:
* VSCode and other editors do this
* It's what users (independent of the first point) appear to want/expect
* Such a placement will work better if we are to also show documentation
for completion items (the candidate list appears below-and-to-the-right)
For those people looking to retain the existing behaviour, please now
add the following to your .vimrc:
call govim#config#Set("ExperimentalMouseTriggeredHoverPopupOptions", {
\ "mousemoved": "any",
\ "pos": "topleft",
\ "line": +1,
\ "col": 0,
\ "moved": "any",
\ "wrap": v:false,
\ "close": "click",
\ …
=> cmd/govim: switch default hover popup to place above-and-to-the-right

cmd/govim/config/minimal.vimrc, cmd/govim/testdata/references.txt
Expand the set of sensible out-of-the-box defaults we recommend in the
minimal .vimrc. In future, as previously discussed, we might want to
make these defaults a part of the govim plugin itself, but for now we
make them as recommendations in the minimal .vimrc
This change includes:
* turning on syntax highlighting for .go files
* turning on smart-autoindent
* setting sensible backspace behaviour
This should give a nicer experience for first-time Vim users.
Fixes #430
=> cmd/govim: expand the set of sensible out-of-the-box defaults

cmd/govim/testdata/quickfix_config.txt, cmd/govim/testdata/signs.txt
It's a bit dirty since it leaks details about the implementation, but at this stage it's better than flaky test imho.
The testscripts will now wait for the appropriate calls to pass.
=> tests: Fix flaky signs & quickfix config tests

cmd/govim/signs.go
This PR move a `BatchStart()`-call to avoid calling non-batch functions during a batch.
I've seen a couple of panics that I think will be fixed with this PR.
=> cmd/govim: move BatchStart to avoid panics

plugin/govim.vim
Move the GOBIN and GO111MODULE environment variable sets into the system call instead of setting them in VIMs shell.
On my system setting GOBIN in VIMs shell then calling system is still resulting in the shell run by system having the GOBIN that's defined in my own environment. GOBIN is defined in my shell rc file so it's possible when system is running the command it's starting a new shell which is setting GOBIN again.
This install command should make less assumptions about the shell underneath VIM and moving the environment variables into the system call makes less since it overrides the variables for that single line being executed rather than changing it for the VIM shell.
Fixes #164
=> cmd/govim: fix setting GOBIN during install

cmd/govim/testdata/goimports.txt
The goimports test sometimes matches an earlier entry when looking for `setfqlist`, this PR will specify that it should match the 5th occasion by adding `-start -count=5`.
Fixes #419
=> cmd/govim: fix flake in goimports testscript

cmd/govim/testdata/signs.txt
This PR fixes flakes in `testdata/signs.txt`. I've observed that the first `sign_getplaced()` can be called before the signs were placed.
Waiting for the actual placelist call instead of the diagnostics callback fixes it.
=> test: flake fixed in signs testscript

plugin/govim.vim
The `MYVAR=myvalue command ...` syntax is a bash-ism, and incompatible with other shells, e.g. [fish](https://fishshell.com). With the code as-is, installing govim using fish fails with the unfortunately cryptic
```
Installing govim and gopls
Error detected while processing function <SNR>20_install:
line   15:
E605: Exception not caught:
Error detected while processing /Users/pbourgon/.vim/pack/plugins/start/govim/plugin/govim.vim:
line  334:
E171: Missing :endif
Press ENTER or type command to continue
```
I've updated to the more widely compatible alternative, `env MYVAR=myvalue command ...`.
=> plugin: govim.vim: fix env var

cmd/govim/internal/stringfns/stringfns.go, cmd/govim/stringfns.go
We were needlessly using an interface{}-value map which lead to a couple
of sloppy bugs. Instead, prefer a properly-typed value and wrap
functions accordingly.
=> cmd/govim: tidy up and fix initial GOVIMStringFn implementation

cmd/govim/testdata/bad_complete.txt, cmd/govim/testdata/command.txt, cmd/govim/testdata/complete.txt, cmd/govim/testdata/complete_watched.txt, cmd/govim/testdata/format_on_save_none.txt, cmd/govim/testdata/function.txt, cmd/govim/testdata/function_hover.txt, cmd/govim/testdata/go_to_def_newtab.txt, cmd/govim/testdata/go_to_def_same_file.txt, cmd/govim/testdata/go_to_def_split.txt, cmd/govim/testdata/go_to_def_useopen.txt, cmd/govim/testdata/go_to_def_usetab.txt, cmd/govim/testdata/go_to_def_vsplit.txt, cmd/govim/testdata/gofmt.txt, cmd/govim/testdata/goimports.txt, cmd/govim/testdata/hover.txt, cmd/govim/testdata/mapping_defaults_go_to_def.txt, cmd/govim/testdata/quickfix.txt, cmd/govim/testdata/quickfix_config.txt, cmd/govim/testdata/quickfix_eof.txt, cmd/govim/testdata/references.txt, cmd/govim/testdata/signs.txt
Most of the testscript files checks for errors by matching a `LogMessage callback:` string. It does however contain `%v` so will never match any errors.
This change will make them check for `LogMessage` callbacks of type 1 or 2 (i.e. [warnings or errors](https://microsoft.github.io/language-server-protocol/specification#window_showMessage)) instead.
=> test: fix false positives in testscripts

cmd/govim/hover.go
cmd/govim: do not create a popup if there is a zero Hover response
Currently, we show a popup in the case there is no error in the call to
Hover. However, we do not check that there is actually anthing to show.
Following https://go-review.googlesource.com/c/tools/+/186997/, the
Hover LSP method swallows errors where the user hovered over an area
where there is no information. So now we get back nil errors and empty
Hover{} values where before we got an error (which we simply logged).
Correct this by only showing a popup in case we have a non-zero value
Hover{}.
=> cmd/govim: do not create a popup if there is a zero Hover response

cmd/govim/internal/fswatcher/fswatcher.go, cmd/govim/internal/fswatcher/os_darwin.go, cmd/govim/internal/fswatcher/os_others.go, cmd/govim/testdata/watcher.txt, cmd/govim/watcher.go, go.mod, go.sum
As the current filesystem watcher is using `fsnotify/fsnotify` and opens up loads of files this PR will change the macOS implementation to use `fsnotify/fsevents` instead.
Pro's about this is that `fsevents` watches recursively so the implementation is fairly simple.
Con's about this is that it doesn't support module directories that spawns over several devices as the device must be specified when the watcher is created. There is an open issue, https://github.com/fsnotify/fsevents/issues/36, that prevents adding multiple paths.
I guess we could add several watchers to handle that case, but I'm not sure it's worth it as the watchers should go away as soon as they are added to gopls anyway.
Another option could be to allow macOS users to use the "legacy fsnotifiy" with an env var, in case …
=> cmd/govim: add separate watcher for darwin

cmd/govim/testdata/bad_complete.txt, cmd/govim/testdata/command.txt, cmd/govim/testdata/complete.txt, cmd/govim/testdata/complete_watched.txt, cmd/govim/testdata/format_on_save_none.txt, cmd/govim/testdata/function.txt, cmd/govim/testdata/function_hover.txt, cmd/govim/testdata/go_to_def_newtab.txt, cmd/govim/testdata/go_to_def_same_file.txt, cmd/govim/testdata/go_to_def_split.txt, cmd/govim/testdata/go_to_def_useopen.txt, cmd/govim/testdata/go_to_def_usetab.txt, cmd/govim/testdata/go_to_def_vsplit.txt, cmd/govim/testdata/gofmt.txt, cmd/govim/testdata/goimports.txt, cmd/govim/testdata/hover.txt, cmd/govim/testdata/mapping_defaults_go_to_def.txt, cmd/govim/testdata/quickfix.txt, cmd/govim/testdata/quickfix_config.txt, cmd/govim/testdata/quickfix_eof.txt, cmd/govim/testdata/quickfix_retain_position.txt, cmd/govim/testdata/references.txt, cmd/govim/testdata/signs.txt, cmd/govim/testdata/watcher.txt
In 3d166ac we fixed the fact that we had false-positive checks on the
number of errors being reported by gopls. However, fixing this uncovered
https://github.com/golang/go/issues/34103. So for now, disable those
errlogmatch-based checks, pending a fix on the "noise" from gopls of
errors that are not actually errors.
=> cmd/govim: disable testscript checks for the number of errors

cmd/govim/testdata/motion.txt, cmd/govim/testdata/motion_bad_ast.txt, ftplugin/go.vim
```
Currently we have ]] mapped to:
:call GOVIMMotion("next", "File.Decls.End()")
and ][ mapped to:
:call GOVIMMotion("next", "File.Decls.Pos()")
But this is the inverse of the Vim-default mappings we are looking to
"emulate":
]]  [count] sections forward or to the next '{' in the
first column.  When used after an operator, then also
stops below a '}' in the first column.  exclusive
Note that exclusive-linewise often applies.
][  [count] sections forward or to the next '}' in the
first column.  |exclusive|
Note that |exclusive-linewise| often applies.
Fix this by invertig our mapping.
```
=> cmd/govim: fix incorrect motion mapping

cmd/govim/textedit.go
Would have helped to accurately diagnose #486
=> cmd/govim: properly capture error message when ioutil.TempFile fails

cmd/govim/test_config.go, cmd/govim/testdata/batch.txt, cmd/govim/vimstate.go
We should panic if we attempt to call a non-batch channel method when in a batch.
Fixes #438
=> cmd/govim: prevent non-batch calls being called when in batch

go.mod, go.sum
- testscript: make sure work dir isn't removed when -testwork is used (#80) 18d060b
- testscript: ensure that temp dir isn't sym-linked (#79) 9181448
Closes #456 
Closes #308
=> deps: update rogpeppe/go-internal to v1.3.2

.travis.yml, _scripts/genconfig.go
Further attempt to get our Travis email notification setup "right" now
that we are using the govim-dev+ci group for build notifications
=> ci: never notify for successful builds, only notify on failure

cmd/govim/config/config.go, cmd/govim/main.go, cmd/govim/main_test.go
Per @cespare's motivation, this allows users to use a (company)
standardised version of gopls and upgrade a rate different to that of
govim. This is important for things like handling gofmt changes between
Go versions.
However, use of this environment variable comes with zero warranty,
because it's not guaranteed that govim's tests pass/work at all with
whatever version of gopls is found in PATH.
Fixes #440
=> cmd/govim: provide advanced env var to use gopls from PATH

cmd/govim/testdata/quickfix_config.txt, cmd/govim/testdata/references.txt, cmd/govim/testdata/signs.txt
Follow up to 01d4e82; we missed dropping some condition references to
[!v8.1.1711] which is used to refer to versions prior to the now-minimum
version.
For #518
=> all: drop any references to now-old Vim versions

README.md, cmd/govim/config/minimal.gvimrc, testdriver/testdriver.go
Now that Vim supports popups for the info of a completion candidate, and
that popup window can be positioned relative to the candidates menu,
provide a version-guarded suggestion in the minimal.vimrc.
Also create a minimal.gvimrc so that Gvim users don't miss out on this
suggestions. This will require a tweak to the wiki in a couple of
places.
Fixes #392
=> cmd/govim: add info popup config to minimal.vimrc; add minimal.gvimrc

cmd/govim/gopls_client.go, cmd/govim/watcher.go, event_queue.go, govim.go, plugin/govim.vim, testdriver/testdriver.go
Currently we have the concept of scheduling via Govim.Schedule, where
non-Vim events (e.g.  diagnostics being sent from gopls) can schedule
work to happen in the govim event queue.
However this approach leads to race conditions: non-Vim events and Vim
events are, by definition, not synchronised.
Calls from Vim -> govim use ch_evalexpr, meaning the caller (in Vim) is
blocked. But whilst blocked, Vim can (and does) process messages
received over the channel from govim. This can (and does) include messages from
govim that include function calls, expressions and commands. Similarly,
a call from govim -> Vim from the govim event queue (i.e. a scheduled
call or a callback from Vim) blocks. But govim can (and does) process
messages received over the channel from Vim. This includes autocommands, …
=> govim: refactor the way we schedule work in Vim

cmd/govim/diagnostics.go, cmd/govim/gopls_client.go, cmd/govim/internal/types/types.go, cmd/govim/quickfix.go, cmd/govim/signs.go, cmd/govim/vimstate.go
To be able to add highlighting of diagnostics (over the entire range), diagnostics hovering, etc. we need to extract more things from the LSP diagnostics, like range and severity.
Much of the current logic take place inside the quickfix handling today, and the idea with this change is to move the generic stuff out from the quickfix specific code. That includes sign placement as well, but we still want to ensure a consistent state where signs always represents what is shown in the quickfix list.
=> [WIP] cmd/govim: refactor diagnostics handling

autoload/govim/config.vim, cmd/govim/config/config.go, cmd/govim/format.go, cmd/govim/gopls_client.go, cmd/govim/hover.go, cmd/govim/internal/vimconfig/vimconfig.go, cmd/govim/main.go, cmd/govim/signs.go, cmd/govim/testdata/goimports.txt, cmd/govim/testdata/quickfix_config.txt, cmd/govim/testdata/references.txt, cmd/govim/vimstate.go
This is a breaking change.
In line with a recent change in gopls, move from negative options like
QuickfixAutoDiagnosticsDisable to QuickfixAutoDiagnostics. This requires
that we introduce the concept of a config value not having been set,
hence the cmd/govim/config.Config type now has pointer type fields.
=> [WIP] cmd/govim: move to positive options and move defaults to constructor

cmd/govim/gopls_client.go
Because we don't yet have tests for the disabling of fuzzy and deep
completion (#520) we missed the fact that gopls deprecated
disableDeepCompletion and disableFuzzyMatching.
The deprecation message comes as a warning via ShowMessage. We currently
only show errors and hence missed this.
"Fix" this be also showing warnings.
=> cmd/govim: also show gopls ShowMessage warning messages

govim.go
This change should have been made as part of e805441 because in making
the changes to change the scheduling approach, we effectively dropped
the fact that a scheduled call is "guarded" by a recover from a govim
shutdown. Hence we re-add that in this change.
=> govim: handle shutdown within Schedule

autoload/govim/config.vim, cmd/govim/testdata/scenario_caseinsensitivecompletion/no_fuzzy_no_deep.txt
Use helper functions where we can to reduce the boilerplate and
copy-paste in the autoloaded Vimscript used for validation on the Vim
side.
=> cmd/govim: tidy up Vim-side validation

autoload/govim/config.vim, cmd/govim/config/config.go, cmd/govim/gopls_client.go, cmd/govim/internal/vimconfig/vimconfig.go, cmd/govim/main.go, cmd/govim/testdata/scenario_staticcheck/default_config.json, cmd/govim/testdata/scenario_staticcheck/staticcheck.txt
Disable staticcheck by default for now whilst we iron out inevitable
issues.
Add a test to verify it works.
=> cmd/govim: add config to enable staticcheck within gopls

cmd/govim/config/config.go, cmd/govim/internal/util/util.go, cmd/govim/main.go
This change adds a new environment variable, GOVIM_GOPLS_FLAGS, that is used to pass additional flags to gopls.
=> cmg/govim: add env var to pass flags to gopls

cmd/govim/buffer_events.go, cmd/govim/diagnostics.go, cmd/govim/internal/types/types.go, cmd/govim/main.go, cmd/govim/references.go, cmd/govim/util.go
To be able to use textprops for highlighting, we must be aware of
if a buffer is loaded or not. Text properties can't be added to
unloaded buffers, and trying to do so will throw an "invalid line"
error.
This change keeps track of if buffers are loaded or not.
=> cmd/govim: keep track of if buffers are "Loaded" or not

cmd/govim/diagnostics.go, cmd/govim/internal/types/types.go, cmd/govim/signs.go, cmd/govim/testdata/scenario_default/quickfix_config.txt, cmd/govim/testdata/scenario_default/signs.txt, ftplugin/go.vim
This change adds default highlights for the different LSP severities.
They can all be overridden in your .vimrc to match your theme. If you
for example would prefer blue background for errors in your color
terminal you'd add this line to your .vimrc:
hi govimErr ctermbg=Blue
The different highlight names are:
- govimErr
- govimWarn
- govimInfo
- govimHint
This is also a gardening change for diagnostics highlights that will
use the same defined highlights.
=> cmd/govim: add highlights for all LSP severities and use them for signs

cmd/govim/diagnostics.go, cmd/govim/gopls_client.go, cmd/govim/main.go, cmd/govim/suggested_fixes.go, cmd/govim/vimstate.go
This change will use lazy conversion of incoming LSP diagnostics.
We use incoming diagnostics for both quickfix and sign placement,
and will also use them for highlighting. Vim handles each of them
differently when it comes to removing entities so we need a way
to get the latest diagnostics that doesn't perform conversion each
call.
=> cmd/govim: refactor diagnostics handling to use lazy conversion

cmd/govim/buffer_events.go, cmd/govim/diagnostics.go, cmd/govim/main.go, cmd/govim/quickfix.go, cmd/govim/references.go, cmd/govim/testdata/scenario_default/signs.txt, cmd/govim/testdata/scenario_default/signs_existing_diags.txt, cmd/govim/vimstate.go
If gopls report diagnostics for files that aren't opened in vim
they won't get any signs placed when they are opened.
A typical use case is when staticcheck report diagnostics for
a file that isn't opened, and the user uses quickfix to jump
directly to the issue (effectively opening a new buffer).
This change updates the internal diagnostics cache when a buffer
is read or closed so existing diagnostics will have signs placed.
=> cmd/govim: place signs for existing diagnostics in new buffers

cmd/govim/testdata/scenario_caseinsensitivecompletion/complete.txt, cmd/govim/testdata/scenario_caseinsensitivecompletion/no_fuzzy_no_deep.txt, cmd/govim/testdata/scenario_casesensitivecompletion/complete.txt, cmd/govim/testdata/scenario_completeunimported/complete.txt, cmd/govim/testdata/scenario_default/complete.txt, cmd/govim/testdata/scenario_default/complete_deep_fuzzy.txt, cmd/govim/testdata/scenario_default/complete_watched.txt, cmd/govim/testdata/scenario_default/go_to_def_usetab.txt, cmd/govim/testdata/scenario_default/gofmt.txt, cmd/govim/testdata/scenario_default/gofmt_eof.txt, cmd/govim/testdata/scenario_default/goimports.txt, cmd/govim/testdata/scenario_default/goproxytest_usage.txt, cmd/govim/testdata/scenario_default/mapping_defaults_go_to_def.txt, cmd/govim/testdata/scenario_default/quickfix.txt, cmd/govim/testdata/scenario_default/quickfix_config.txt, cmd/govim/testdata/scenario_default/quickfix_eof.txt, cmd/govim/testdata/scenario_default/quickfix_retain_position.txt, cmd/govim/testdata/scenario_default/references.txt, cmd/govim/testdata/scenario_default/rename.txt, cmd/govim/testdata/scenario_default/show_message.txt, cmd/govim/testdata/scenario_default/signs.txt, cmd/govim/testdata/scenario_default/signs_existing_diags.txt, cmd/govim/testdata/scenario_default/suggested_fixes.txt, cmd/govim/testdata/scenario_default/watcher.txt, cmd/govim/testdata/scenario_goimports_local/existing_import.txt, cmd/govim/testdata/scenario_goimports_local/new_import.txt, cmd/govim/testdata/scenario_no_quickfixautodiagnostics/signs.txt, cmd/govim/testdata/scenario_staticcheck/staticcheck.txt, testdriver/testdriver.go
errlogmatch's -wait flag is now optional. It's value is taken from
os.Getenv("GOVIM_ERRLOGMATCH_WAIT") else it is 30s, the current value.
Closes #607
=> tests: define a default value for errlogmatch -wait flag

cmd/govim/main_test.go, go.mod, go.sum, testdriver/testdriver.go
Per the deprecation policy for github.com/kr/pty:
> This package is deprecated. Existing clients will continue to work,
but no further updates will happen here. New clients should use
github.com/creack/pty directly.
we are switching to github.com/creack/pty.
Closes #623
=> deps: switch to github.com/creack/pty

_scripts/dockerRun.sh, cmd/govim/main_test.go
=> cmd/govim: put install scripts tests behind env var

testdriver/testdriver.go
Running the tests in macOS will bring up a dialog from the firewall
prompting to allow an unsigned process to listen to network connections.
Using local loopback interface instead for the testdriver will please the
firewall and no dialog shows.
=> testdriver: limit listening to local interface

autoload/govim/config.vim, cmd/govim/buffer_events.go, cmd/govim/config/config.go, cmd/govim/config/gen_applygen.go, cmd/govim/diagnostics.go, cmd/govim/highlight.go, cmd/govim/internal/types/types.go, cmd/govim/internal/vimconfig/vimconfig.go, cmd/govim/main.go, cmd/govim/signs.go, cmd/govim/testdata/scenario_default/diagnostic_highlights.txt, cmd/govim/testdata/scenario_default/quickfix_config.txt, cmd/govim/testdata/scenario_default/signs.txt, cmd/govim/testdata/scenario_default/signs_existing_diags.txt, cmd/govim/testdata/scenario_no_quickfixautodiagnostics/signs.txt, cmd/govim/vimstate.go, ftplugin/go.vim
Diagnostics from gopls will now be highlighted directly in the code. There are four different highlights that can be overridden in vim to use different styles/colors for each of the LSP severities Error, Warning, Info and Hint.
Note that this change also renames sign highlights, which is a breaking change for anyone that use custom colors for their signs.
[![asciicast](https://asciinema.org/a/33WJNxjZs1vdZQYWv4DwVy6qr.svg)](https://asciinema.org/a/33WJNxjZs1vdZQYWv4DwVy6qr)
=> cmd/govim: text propoperty highlight diagnostics

cmd/govim/testdata/scenario_default/quickfix_config.txt
In light of recent changes in gopls to not sent diagnostics for files
when those diagnostics have not changed, we need to slightly tweak our
assertions in various testscript scripts.
This is first such change. Others will/may follow
=> cmd/govim: tighten up quickfix config tests

plugin/govim.vim
We have, over time, seen a number of flakes where we appear to be
missing autocmd callbacks. The most prominent of these is in the rename
tests where we fail to see autocmd callbacks for an unopen file we have
just split/vsplit etc. This could point towards a Vim bug, but more
likely is that fact that each of these flakes is interacting with the
user-busy logic.
Key in this analysis is a callstack from a recent flake:
SNR>18_userBusy[3]..GOVIM_internal_SetUserBusy[2]..<SNR>18_callbackFunction[2]..<SNR>18_ch_evalexpr[15]..<SNR>18_drainScheduleBacklog[14]..<SNR>18_ch_evalexpr[10]..<SNR>18_define[40]..<SNR>18_callbackCommand[3]..<SNR>18_ch_evalexpr
Notice at the bottom (left) of the callstack is userBusy. Currently we
do not have ++nested on the definition of the autocmd that fires when
the …
=> cmd/govim: make user busy autocmd nested

cmd/govim/testdata/scenario_default/complete.txt
As previously discovered (and also raised in #658), 11eb9c7 caused
completion to break in govim because placeholder values are now included
in the completion result. This has now been fixed in:
https://go-review.googlesource.com/c/tools/+/213640
However, because of a bug introduced in:
https://go-review.googlesource.com/c/tools/+/212102
we can't simply upgrade to the latest x/tools and gopls.
In any case we want to add a test to demonstrate the problem and prevent
and future regressions. A subsequent PR will upgrade the version of
x/tools and gopls to a commit (in a temporary fork) that has the fix for
the completion bug but does not have the bug for the parallel initial
load.
Updates #658
=> cmd/govim: create a test demonstrating failing completion

ftdetect/go.vim, indent/gomod.vim, syntax/gomod.vim
First, add ftdetect configuration to detect go.mod files as the 'gomod' filetype.
Then add syntax and indent files for this filetype.
The gomod syntax file is reused from the vim-go project under the terms of its 3-clause BSD license. The indent file is new work.
=> Detect go.mod as a 'gomod' filetype; add syntax and indent

_scripts/dockerRun.sh
The master CRON build that happens on Travis should be checking against
master of x/tools and gopls. To ensure we actually test against x/tools
and gopls master we need to make sure that there are no replace
directives against either module.
This PR fixes that.
=> ci: fix master cron build to drop replace directives

_scripts/afterFailure.sh, cmd/govim/main.go, cmd/govim/main_test.go, plugin/govim.vim
A minor annoyance, but when reporting issues via GitHub, uploading log
files only works in the browser if the file has a .log extension. Our
log file templates do not currently have such an extension which means
manual renaming is required before the file can be uploaded.
Fix that.
=> cmd/govim: change log file template to default to .log files

cmd/govim/main_test.go, go.mod, go.sum, govim_test.go
In 854efaeb we included a temporary hack for setting the destination of
artefacts for testscript tests, via GOTMPDIR. In this commit we undo
that hack.
Motivation for the change best described in:
rogpeppe/go-internal@bc89b17
=> testing: revert GOTMPDIR hack for setting testscript workdir root

_scripts/afterFailure.sh, _scripts/captureLogs.sh, _scripts/tidyUp.bash
When the CI build fails and generates artefacts we capture logs.
Sometimes it's useful to be able to do that locally.
_scripts/captureLogs.sh makes that trivial by wrapping the relevant
commands.
=> scripts: add captureLogs.sh to easily run tests and capture all logs

cmd/govim/complete.go, cmd/govim/main.go, cmd/govim/testdata/scenario_completeunimported/complete.txt, cmd/govim/testdata/scenario_default/complete_watched.txt, complete.go
Some completion candidates, most notably unimported completion
candidates, carry with them additional text edits. In the case of
unimported candidates, these represent the changes required to add the
missing import if the candidate is chosen.
This commit applies those text edits when we get the event CompleteDone.
=> cmd/govim: apply AdditionalTextEdits on CompleteDone

autoload/govim/config.vim, cmd/govim/config/config.go, cmd/govim/config/gen_applygen.go, cmd/govim/diagnostics.go, cmd/govim/highlight.go, cmd/govim/hover.go, cmd/govim/internal/types/types.go, cmd/govim/internal/vimconfig/vimconfig.go, cmd/govim/main.go, cmd/govim/testdata/scenario_default/function_hover.txt
When using the hover feature, either via keyboard or mouse, any
diagnostics with a range that covers the current position will
be added at the top of popup.
The diagnostics are formatted using text properties, and as a
consequence of this there are a few new highlight groups defined:
* GOVIMHoverErr
* GOVIMHoverWarn
* GOVIMHoverInfo
* GOVIMHoverHint
The diagnostic line also includes the diagnostic source (as
provided by gopls, e.g. "compiler", "printf", "unreachable").
To be able to format the source there is another highlight group
used for the source part:
* GOVIMHoverDiagSrc
All text properties are combined with existing syntax highlight
to enable a wide range of custom styles.
The feature is enabled by default, and can be disabled by setting
the config HoverDiagnostics to 0 (false). …
=> cmd/govim: add diagnostics to hover popup

_scripts/runDockerRun.sh, cmd/govim/cleanup1.14_test.go, cmd/govim/cleanup_pre1.14_test.go, cmd/govim/main_test.go, go.sum
Our cmd/govim testscript tests are split across a number of directories.
This grouping allows us to have separate configuration per directory.
Currently we do not call t.Parallel in each directory's subtest. This
means that we run directory scipts in serial, one directory after
another. Therefore, if there is a particularly slow test in one
directory, we can end up with flat spots where we do not fully utilise
the -test.parallel concurrency limit.
Making directory subtests parallel removes these flat spots. But we do
so at the cost of leaving beind gopls install artefacts. When we start
testing against a Go 1.14 release that includes CL 214822 we can enable
that cleanup, but Go version pre 1.14 will unfortunately continue to
leak these artefacts.
=> cmd/govim: make testscript scripts truly concurrent

cmd/govim/buffer_events.go, cmd/govim/diagnostics.go, cmd/govim/gopls_client.go, cmd/govim/highlight.go, cmd/govim/main.go, cmd/govim/vimstate.go
The diagnostic highlights were always updated when leaving userbusy.
If the buffer changed since the last diagnostic received from gopls,
we might end up with a buffer that doesn't contain the lines/cols
where we try to place text properties. That did thrown an error.
This fix adds the same logic that exists for other diagnostic
features, so that leaving userbusy only triggers text property
placment if there are new diagnostics.
=> cmd/govim: leaving userbusy always updates text property highlighs

cmd/govim/main_test.go
In testscript tests, Vim is opened with a working directory of the
workdir. This means that the govim file watcher is watching every file
beneath that directory (every file not hidden, that is).
GOPATH is currently $WORK/gopath which means that the govim file watcher
will, incorrectly, be spotting .go files that change within the module
cache.
Fix this be explicitly putting GOPATH within $HOME which is already
defined as $WORK/.home
=> cmd/govim: ensure that GOPATH is in a hidden directory

cmd/govim/testdata/scenario_goimports_local/existing_import.txt
Per https://github.com/vim/vim/issues/5507#issuecomment-576825067,
scenario_goimports_local/existing_import.txt is known to be flakey for
GVim v8.1.1711. Whilst we understand the underlying reason in that
thread, we choose to skip this test on the understanding the flake is
related to a Vim bug of some sort.
=> cmd/govim: skip flakey test for GVim v8.1.1711

.travis.yml, _scripts/genconfig.go
Currently we never notify for a green build on master. This isn't very
helpful because it means we don't get a notification when the build
passes having previously failed, i.e. red -> green.
Fix that to notify on change.
=> ci: notify when the master build goes green

govim_test.go
This is a follow up to 57e94a3 because we missed the testscript tests in
the module root.
=> govim: make testscript tests truly concurrent

cmd/govim/testdata/scenario_bugs/bug_govim_688.txt, cmd/govim/textedit.go
Add a test to ensure (at least against the current behaviour of gopls)
we don't regress here.
Fixes #688
=> cmd/govim: skip empty text edits

cmd/govim/config/config.go, cmd/govim/gopls_client.go
Useful for debugging gopls issues.
=> cmd/govim: provide env var to turn on gopls verbose output

cmd/govim/testdata/scenario_tempmodfile/modfile_changes.txt
Make sure we are consistent in our use of GOVIMTest_getqflist
=> cmd/govim: fix a rogue use of getqflist in a testscript test

cmd/govim/highlight.go, cmd/govim/vimstate.go
The config HighlightDiagnostics can be used to disable in-code
highlights. PR #700 accidently broke that feature so that it was
possible to get highlights even when disabled.
This PR ensures that text prop highlights aren't placed when they
are disabled by the config.
Fixes #724
=> cmd/govim: Ensure text prop highlights aren't placed when disabled

cmd/govim/testdata/scenario_default/go_to_def_module_cache.txt, cmd/govim/testdata/scenario_default/go_to_def_std_lib.txt
Extend our suite of go-to-def tests by adding two new tests that jump to
standard library and module cache definitions.
=> cmd/govim: add go-to-def tests for std lib and module cache definitions

cmd/govim/testdata/scenario_default/rename.txt
Following golang.org/issues/36743 it became clear didn't have a test
case covering that scenario. Create one.
Skip that test for now until the fix for golang.org/issues/36743 lands.
=> cmd/govim: add a test that renames an identifier in another package

_scripts/runDockerRun.sh, _scripts/tagDockerLatest.sh
Update the :latest tag for govim images. By default only runs on CI whilst
building against the master branch. This isn't totally foolproof, but good
enough for what we need
=> ci: tag docker :latest-vim on CI master builds

cmd/govim/testdata/scenario_default/complete_module_cache.txt, cmd/govim/testdata/scenario_default/complete_std_lib.txt
Extend our suite of completion tests by adding two new tests that
complete standard library and module cache definitions.
=> cmd/govim: add completion tests for std lib and module cache definitions

cmd/govim/testdata/scenario_completeunimported/complete_new_file.txt, cmd/govim/testdata/scenario_default/quickfix_new_files.txt, cmd/govim/testdata/scenario_default/rename.txt, cmd/govim/testdata/scenario_modfile/go_local_mod.txt, cmd/govim/testdata/scenario_modreadonly/config_set_env_goflags_mod_readonly.txt, testdriver/testdriver.go, testsetup/testsetup.go
Some of our testscript tests are skipped because they are dependent on
fixes for issues that remain open, i.e. the fixes have not landed. We
try to annotate this skips with an appropriately structured comment,
e.g.:
skip 'Pending fix for golang.org/issues/36789'
However, this approach makes it hard to not skip the test when you are
looking to verify a fix. We end up having to suggest a sed command (or
similar) to remove/comment out the skip.
Instead we now provide a custom testscript condition that allows issue
tracker links as the condition itself, e.g.
[golang.org/issues/36789] skip
[github.com/govim/govim/issues/1234] skip
This means we retain the structure and linkage of the current approach.
Such a condition is always satisfied unless the the
GOVIM_TESTSCRIPT_ISSUES environment …
=> tests: add testscript condition for issues

cmd/govim/internal/golang_org_x_tools/lsp/cache/load.go, cmd/govim/internal/golang_org_x_tools/lsp/cache/snapshot.go, cmd/govim/internal/golang_org_x_tools/lsp/cache/view.go, cmd/govim/internal/golang_org_x_tools/lsp/source/diagnostics.go, go.mod, go.sum
* all: revert uses of types.NewInterfaceType 2f3ba24b
* internal/lsp: set workspace packages during (*snapshot).load 4e655657
* internal/lsp/mod: fix test that checks for unchanged go.mod c8253cff
* internal/lsp/cache: move shouldLoad function to snapshot.go 8a05c59e
* internal/lsp/cache: use telemetry logging for imports refresh 71655563
* internal/lsp/source: check cancellation before analysis ec2e11d2
* internal/lsp/cache: delete a few unused functions 11f6c2ac
=> deps: upgrade x/tools and gopls to 2f3ba24b

cmd/govim/highlight.go, cmd/govim/internal/types/types.go, cmd/govim/vimstate.go
This change extracts text property removal to it's own func.
It acts as gardening for implementing references highlights where we'll
start using another text property ID, and therefore it is added as an
internal type.
=> cmd/govim: extract text property removal to own func

_scripts/dockerRun.sh, internal/cmd/dots/dots.go, testdriver/testdriver.go, testsetup/norace.go, testsetup/race.go, testsetup/testsetup.go
When we run tests under race mode, all timings are slowed by some
factor. This means that tests which sleep in order to ensure, for
example, that no diagnostics are received, potentially have a higher
chance of passing with false negatives, i.e. they stop looking for
diagnostics too early.
Fix this by introducing a race slowdown factor which we set initially as
2.
=> tests: add testsetup.RaceSlowndownFactor

cmd/govim/internal/golang_org_x_tools/span/uri.go, go.mod, go.sum
* go/packages: fix non-determinism on package list order fe90550f
* internal/span: always uppercase the drive letter for Windows 07253810
* go/packages: make TestOverlayDeps deterministic 90908045
* go/packages: work around pkg-config errors in go list 449c356b
* go/packages: add a workaround for golang/go#36188 71629799
=> deps: upgrade x/tools and gopls to fe90550f

.github/workflows/test.yml, internal/cmd/genconfig/genconfig.go
Otherwise we don't get to enjoy the benefits of a full matrix of flakes.
=> ci: do not fail-fast on failures

cmd/govim/testdata/scenario_default/go_to_def_same_file.txt
In e5653c8e we sort to make go-to-def testscript tests go.mod stable. We
missed an instance as part of that change. Fix that.
=> cmd/govim: really ensure go-to-def tests have stable go.mod files

.github/workflows/test.yml, internal/cmd/genconfig/genconfig.go
Per this thread:
https://twitter.com/_myitcv/status/1223329679442173953
using short-hand major versions for actions, e.g.:
actions/checkout@v1
is brittle. Per the rest of the thread, using even full semver versions
is brittle because it's so easy to move tags on GitHub.
Therefore using commit hashes is the best of a bad bunch right now.
Given:
https://twitter.com/_rsc/status/1088109141409837063
we are still not, however, out of the woods because we are not
guaranteed to run exactly the transitive dependencies tomorrow that we
ran today.
This is all somewhat moot because we are running CI on GitHub
infrastructure, but let's try to make this as safe as possible given the
tools we have.
=> ci: use specific commits of actions

cmd/govim/buffer_events.go, cmd/govim/config/config.go, cmd/govim/internal/fswatcher/fswatcher.go, cmd/govim/internal/fswatcher/os_darwin.go, cmd/govim/internal/fswatcher/os_others.go, cmd/govim/main.go, cmd/govim/main_test.go, cmd/govim/testdata/scenario_default/complete_watched.txt, cmd/govim/testdata/scenario_default/watcher.txt, cmd/govim/vimstate.go, cmd/govim/watcher.go
Now that gopls supports the didChangeWatchedFiles notification, govim no
longer needs to synthetically open files on external file changes.
This change updates the fswatcher package, along with watcher.go, to use
didChangeWatchedFiles. Notably, this change requires tracking file
creation separately from modification or removal.
Tests are updated to exercise some of this new behavior.
Fixes #187
=> cmd/govim: switch to the didChangeWatchedFiles API

cmd/govim/complete.go, cmd/govim/testdata/scenario_default/complete_watched.txt
As part of the current completion code that handles applying of
additional text edits we have:
for _, c := range v.lastCompleteResults.Items {
if c.Label == chosen.Abbr {
match = &c
}
}
In a previous change, compltion items changes from being a pointer to a
non-pointer value. Hence we flipped the setting of match from c to &c.
But we forgot the break (which arguably could/should have been there
before). Which means that a further iteration of the for loop after a
match will cause the match to find the text edits from another match.
Specifically, we will be left with the additional text edits from the
last match in the list.
Fix that by breaking out of the loop on a match.
As part of this also fix a test which was incorrectly updated as a
result of this bug (which actually makes the bug …
=> cmd/govim: fix embarrassingly bad bug in completion textedit handling

.github/workflows/test.yml, _scripts/common.bash, _scripts/postRun.sh, internal/cmd/genconfig/genconfig.go
Jobs that are skipped in WIP branches have no $ARTEFACTS directory
so those will fail during post run.
This change adds a branchCheck to exit gracefully.
=> ci: add branchCheck to postRun script

cmd/govim/internal/fswatcher/os_darwin.go
Darwin has a separate file system watcher, and it might emit events
that includes both "Created" and "Changed" flag in the same event.
Since the flag "checked" is checked before "created", the darwin
implementation will skip to report "created" if both files exist.
It looks like it only affects tests at the moment (see comments
in #759).
This fix alters order so that only "created" is reported if both
flags exist.
Fixes #759
=> cmd/govim: fix darwin file system watcher event check

cmd/govim/testdata/scenario_completeunimported/complete_empty_file.txt, cmd/govim/testdata/scenario_default/format_on_save_empty_original_file.txt, cmd/govim/testdata/scenario_default/quickfix_empty_files.txt
We have a number of tests that check gopls behaviour where files do not
exist on disk, i.e. they are just buffers in memory. But we are missing
tests to verify that if .go files on disk are empty and then "filled in"
by changes in the editor, that things work as expected.
Add some tests of that sort.
=> cmd/govim: add tests for gopls features where files are initially empty

autoload/govim/config.vim, cmd/govim/config/config.go, cmd/govim/config/gen_applygen.go, cmd/govim/gopls_client.go, cmd/govim/internal/vimconfig/vimconfig.go, cmd/govim/main.go, cmd/govim/testdata/scenario_tempmodfile/user_config.json
The equivalent gopls setting has already been promoted to a "production"
config setting.
We also set a govim-level default of false for now.
=> cmd/govim/config: promote ExperimentalTempModfile to TempModfile

cmd/govim/signs.go
There are, at lest in theory, cases where we try to place signs
in a buffer that was just closed.
To avoid throwing an error to the user if this happens, this
change suppress those errors.
Updates #685
=> cmd/govim: Suppress "invalid buffer" errors when placing signs

autoload/govim/config.vim, cmd/govim/config/config.go, cmd/govim/config/gen_applygen.go, cmd/govim/highlight.go, cmd/govim/internal/types/types.go, cmd/govim/internal/vimconfig/vimconfig.go, cmd/govim/main.go, cmd/govim/testdata/scenario_default/reference_highlight.txt, cmd/govim/vimstate.go
This change adds reference highlighting of the thing under the cursor,
when the user goes idle. As soon as the user goes idle, it will send a
documentHighlight request to gopls, and add a text property according to
the response.
To alter style/format, override the highlight group GOVIMReferences with
your prefered highlight setting.
=> cmd/govim: add reference highlighting when user goes idle

cmd/govim/config/config.go, cmd/govim/highlight.go, cmd/govim/main.go, cmd/govim/vimstate.go
Users might not want the automatic reference highlighting, but still
be able to use it by triggering in manually.
This change adds the command GOVIMHighlightReferences that can be
used to highlight references even when automatic reference highlights
is disabled.
=> cmd/govim: add support for manually triggered reference highlight

.github/workflows/test.yml, govim.go, internal/cmd/genconfig/genconfig.go
The refactor in #784 uncovered a bug which showed, in race tests, that
we were not synchronising writes to the *json.Encoder when sending
messages to Vim.
Fix that by using a mutex to guard access.
=> govim: synchronise access to out *json.Encoder

cmd/govim/main_test.go, cmd/govim/testdata/scenario_default/load_initial_file.txt, testdriver/testdriver.go
PR #784 has uncovered a need to be able to load an initial file as part
of a testscript test. Support this by allowing a vim_config.json file to
be present in a test's archive, a JSON file that is parsed and passed to
the testdriver as Vim-specific config.
Add a test to verify that things work as expected.
=> cmd/govim: add support for loading an initial file in testscript tests

cmd/govim/internal/golang_org_x_tools/lsp/cache/view.go, cmd/govim/internal/golang_org_x_tools/lsp/source/completion.go, cmd/govim/internal/golang_org_x_tools/lsp/source/completion_keywords.go, cmd/govim/internal/golang_org_x_tools/lsp/source/util.go, cmd/govim/internal/golang_org_x_tools/lsp/testdata/lsp/primarymod/foo/foo.go, cmd/govim/internal/golang_org_x_tools/lsp/testdata/lsp/primarymod/keywords/keywords.go, cmd/govim/internal/golang_org_x_tools/lsp/testdata/lsp/primarymod/suggestedfix/has_suggested_fix.go, cmd/govim/internal/golang_org_x_tools/lsp/testdata/lsp/primarymod/suggestedfix/has_suggested_fix.go.golden, cmd/govim/internal/golang_org_x_tools/lsp/testdata/lsp/summary.txt.golden, go.mod, go.sum
* gopls: update Staticcheck to 2020.1.2 57f3fb51
* internal/lsp: create more descriptive temp go.mod name 9c32af92
* internal/lsp/regtest: skip flaky TestGoToStdlibDefinition fe62aff3
* internal/lsp/source: improve completions at file scope 8a925fa4
* internal/lsp/regtest: increase test timeout to 60s 947cbf19
=> deps: upgrade x/tools and gopls to 57f3fb51

cmd/govim/gopls_client.go, cmd/govim/main.go
In 2db04e591 we added a workaround for a problem with gopls calling the
client Configuration method out of order. Subsequent changes in gopls
have made this workaround unnecessary. Hence, we now remove that
workaround.
=> cmd/govim: remove govim workaround for Configuration loading

ftdetect/go.vim
In Go 1.14 the -modfile flag lands for cmd/go. This allows an alternate
go.mod file to be provided for reads/writes during module resolution.
The alternate file must have a .mod extension, hence we should update
our file detection logic to be for *.mod.
=> cmd/govim: switch ftdetect for go.mod files to be *.mod

cmd/govim/testdata/scenario_no_completeunimported/no_complete.txt, cmd/govim/testdata/scenario_no_completeunimported/no_complete_empty_file.txt, cmd/govim/testdata/scenario_no_completeunimported/no_complete_new_file.txt, cmd/govim/testdata/scenario_no_completeunimported/user_config.json
Following d80f0e2 unimported completions are turned on by default. This
commit adds tests to ensure setting CompleteUnimported to false disables
completion for unimported packages.
=> cmd/govim: add tests to verify turning off unimported completions works (#687)

cmd/govim/buffer_events.go, cmd/govim/testdata/scenario_default/non_go_file_navigation.txt
We were only setting a buffer's listener to 0 (i.e. no listener) on
unload for buffers that were of interest to gopls. Hence for non-gopls
buffers we were getting strange lifecycle errors.
Add a test to verify that moving around between non gopls buffers works,
a test that failed before this fix.
=> cmd/govim: fix embarrassingly bad bug in buffer listener reset

cmd/govim/buffer_events.go
A buffer name can change as a result of BufReadCmd. Some plugins use
BufReadCmd to handle special reads of files. For example,
github.com/plan9-for-vimspaceplan9-for-vimspace adds an address handler
to BufReadCmd to handle an attempt to open /path/to/file.go:5:6, i.e. at
a specific address (line:col). Most such handlers then fire a BufRead and
BufWinEnter to complete the buffer life-cycle events, at which point we
can correct the name of the buffer.
There is currently no test for this, but it has been verified locally.
=> cmd/govim: handle buffer name changing in BufWinEnter

cmd/govim/buffer_events.go, cmd/govim/testdata/scenario_bugs/bug_vim_5694.txt
Because of https://github.com/vim/vim/issues/5694 we can find ourselves
in a situation where we get a BufDelete or BufWinEnter for a buffer we
know nothing about. Hence we need to ignore the event or force create
that buffer as a workaround respectively.
=> cmd/govim: workaround BufWinEnter without BufNew bug

cmd/govim/internal/golang_org_x_tools/lsp/debug/serve.go, cmd/govim/internal/golang_org_x_tools/lsp/lsprpc/lsprpc.go, cmd/govim/internal/golang_org_x_tools/telemetry/export/export.go, cmd/govim/internal/golang_org_x_tools/telemetry/export/log.go, cmd/govim/internal/golang_org_x_tools/telemetry/export/ocagent/ocagent.go, go.mod, go.sum
* internal/lsp/lsprpc: use localhost for remote gopls debug interface 066e0c02
* internal/telemetry: remove Flush method from exporter 71482053
* go/packages: drop imports of reflect in tests of import graph a628ca32
=> deps: upgrade x/tools and gopls to 066e0c02

cmd/govim/hover.go
In the current gopls implementation, if there is nothing under the
cursor when we call Hover we simply get a zero value protocol.Hover
returned (albeit via a pointer variable).
As of de023d59a5d1 gopls now returns a zero value of type
*protocol.Hover. Hence where we previously assumed we would not get a
nil value we now do.
Fix that.
=> cmd/govim: handle nil response to Hover

cmd/govim/main.go, cmd/govim/watcher.go
There are currently two file watchers being started, one in Init(...)
and one in startGopls(...). This leads to duplicate
DidChangeWatchedFiles calls to gopls.
Remove one of them, as well as a dated comment about this being a
temporary fix.
This change also removes a field "files" (on the modwatcher struct)
that isn't used anymore.
=> cmd/govim: remove one of the file watchers

cmd/govim/testdata/scenario_default/motion.txt, cmd/govim/testdata/scenario_default/motion_bad_ast.txt, ftplugin/go.vim
The "next" mappings are the wrong way around: ]] when to the start of
the next top-level declaration, ][ to the end.
Fix that by switching them around.
=> cmd/govim: fix "next" motion key mappings for top-level declarations

cmd/govim/highlight.go, cmd/govim/main.go, cmd/govim/testdata/scenario_default/busy_state_change_non_go_file.txt, cmd/govim/testdata/scenario_default/reference_highlight.txt, cmd/govim/util.go, cmd/govim/vimstate.go, plugin/govim.vim
In 8926deca we backed out the changes for tracking all buffer changes.
But in so doing we didn't properly handle the situation where the busy
state changes and the cursor is in a non-go file.
Fix that and add a test to verify we don't regress.
Whilst we are at it:
* consistently use GOVIM_test_SetUserBusy in our testscript tests
* slightly refactor the types/consts used for getting the current cursor
position
Fixes #821
=> cmd/govim: safely handle busy state changes for non-.go buffers

govim.go
If Init() fails, for example gopls exits, we might end
up in a deadlock since we don't read the plugin error channel
until after Init().
This change moves the reading goroutine so that it is started before
Init().
=> govim: move plugin errorchan read to avoid deadlock

govim.go
Embarrassing enough PR 828 fixed the deadlock but introduced a data
race where the plugin error channel was read in a goroutine created
before the channel was created.
This change fixes the data race by moving the reading goroutine to be
started after the channel creation.
=> govim: move plugin errorchan read to avoid data race

cmd/govim/testdata/scenario_default/complete_watched.txt
https://golang.org/cl/223877 changed the behavior of `gopls` to prefer unexported symbols to exported ones. Add a `C` prefix to the complete watched tests to avoid relying on this behavior.
=> cmd/govim/testdata/scenario_default: fix complete watched test for latest gopls changes

cmd/govim/testdata/scenario_default/complete_additionaltextedits.txt, plugin/govim.vim
This change adds a test of additional text edits sent by gopls.
Currently there is a data race where govim applies the additional
edits to a stale version of the buffer. The issue is tracked
in #830.
Updates #830
=> test: add test of completion with additional text edits

plugin/govim.vim
Vim v8.2.0452 introduced a bug that affects govim, causing it to hang:
https://groups.google.com/forum/#!msg/vim_dev/AjQA8dE0EpY/miFlLh0PAwAJ
This bug was fixed in v8.2.0466.
Echo an error if the user is found to be using a bad version.
Fixes #837
=> cmd/govim: echoerr when user tries to load using a bad version of Vim

autoload/govim/config.vim, cmd/govim/config/config.go, cmd/govim/config/gen_applygen.go, cmd/govim/internal/vimconfig/vimconfig.go, cmd/govim/main.go, cmd/govim/testdata/scenario_autoreadloadedbuffers/autoread_loaded_buffers.txt, cmd/govim/testdata/scenario_autoreadloadedbuffers/user_config.json, cmd/govim/watcher.go
If a file is updated on disk while it is open in vim, govim/gopls won't
pick up the change automatically.
This change adds a config setting "AutoreadLoadedBuffers" that is used
to reload buffers for files that change outside vim. It requires the
buffer to be "loaded" since it uses "checktime" to reload the file.
This feature is not enabled by default. Add the following to your vimrc
to enable it:
set autoread
set hidden
call govim#config#Set("AutoreadLoadedBuffers", 1)
"set autoread" will suppress a confirmation prompt when a buffer that
isn't modified is reloaded (a prompt will still be shown if the buffer
is modified). This line is optional.
"set hidden" will configure vim to keep buffers loaded when switched,
instead of the default that is to abandon them. This is required for the …
=> cmd/govim: add autoread loaded buffers support

cmd/govim/config/config.go, cmd/govim/implements.go, cmd/govim/main.go, cmd/govim/testdata/scenario_default/implements.txt, cmd/govim/util.go
This change adds the command GOVIMImplements which shows all
interfaces that the identifier under the cursor implements.
Fixes #577
=> cmd/govim: implement Implements in gopls

cmd/govim/internal/golang_org_x_tools/lsp/cache/os_darwin.go, cmd/govim/internal/golang_org_x_tools/lsp/cache/pkg.go, cmd/govim/internal/golang_org_x_tools/lsp/cache/snapshot.go, cmd/govim/internal/golang_org_x_tools/lsp/cache/view.go, cmd/govim/internal/golang_org_x_tools/lsp/cmd/cmd.go, cmd/govim/internal/golang_org_x_tools/lsp/source/completion.go, cmd/govim/internal/golang_org_x_tools/lsp/source/completion_builtin.go, cmd/govim/internal/golang_org_x_tools/lsp/source/diagnostics.go, cmd/govim/internal/golang_org_x_tools/lsp/source/options.go, cmd/govim/internal/golang_org_x_tools/lsp/source/view.go, cmd/govim/internal/golang_org_x_tools/lsp/testdata/lsp/primarymod/append/append.go, cmd/govim/internal/golang_org_x_tools/lsp/testdata/lsp/primarymod/append/append2.go.in, cmd/govim/internal/golang_org_x_tools/lsp/testdata/lsp/summary.txt.golden, cmd/govim/internal/golang_org_x_tools/lsp/tests/util.go, cmd/govim/testdata/scenario_default/signs_unload_load_buffer.txt, go.mod, go.sum
As part of this, unskip the following test:
cmd/govim/testdata/scenario_default/signs_unload_load_buffer.txt
* internal/lsp: fix panic in builtin completions 9fc00b0a
* internal/lsp/source: propose loaded unimported package names first 0a46fa39
* internal/lsp: temporarily disable type error analyzers by default 3304cfb0
* internal/lsp: add a mutex around the view's options 2d9ba733
* internal/lsp/source: add a replacement for experimentalDisabledAnalyses 69646383
Fixes #839
=> deps: update x/tools and gopls to 9fc00b0a

cmd/govim/main.go
Noticed this because of https://golang.org/cl/227033.
=> cmd/govim: remove initialization options since they are outdated

cmd/govim/diagnostics.go, cmd/govim/quickfix.go, cmd/govim/testdata/scenario_bugs/bug_govim_680.txt, cmd/govim/vimstate.go
See the description in the linked issue.
Fixes #680
=> cmd/govim: fix index out of range bug when flipping back to diagnostics

cmd/govim/buffer_events.go, cmd/govim/config/config.go, cmd/govim/highlight.go, cmd/govim/main.go, cmd/govim/vimstate.go
When manually invoking GOVIMHighlightReferences, it makes sense to
persist the highlights for as long as we can. To be safe we assume that
making any change to any .go file will potentially invalidate the
highlighted references (we might relax this at a later stage). We also
add the GOVIMClearReferencesHighlights command to explicitly remove the
highlights.
As part of this same commit we:
* move the definition of currentReferences to vimstate where it belongs
(it is only ever accessed on the vimstate "thread")
* Tidy up and simplify some logic regarding removal of highlights
=> cmd/govim: persist highlights for explicit GOVIMHighlightReferences call

cmd/govim/buffer_events.go
In 3139f797 I incorrectly removed all reference highlights when a delta
is received. However, the logic prior to that change was that highlights
would only be moved (even in insert mode) if the cursor falls outside of
a highlighted range.
Therefore, we adopt exactly the logic that @leitzler proposed in #852 to
only remove highlights on delta if we are in manual highlighting mode.
=> cmd/govim: do not remove highlights on delta when auto-highlighting

cmd/govim/complete.go, complete.go
When it comes to unimported completions, it is entirely possible that
two packages might have the same name. Generally however, we rely
entirely on gopls to "dedupe" the completion candidate list. So make
this change unconditionally is safe.
=> cmd/govim: allow duplicate items in completion candidates

cmd/govim/complete.go
In e10617c6 we permitted "duplicate" candidates in completion results.
(These items are not in fact duplicates because they are distinguished
by their detail.) However, we failed to fix the logic that matches the
chosen completion candidate versus the list of options; we also need to
include the detail.
Fix that and track adding a test in #867.
=> cmd/govim: fix completion candidate additional text edits for dups

cmd/govim/config/config.go, cmd/govim/highlight.go, cmd/govim/hover.go, cmd/govim/internal/types/popup.go, cmd/govim/main.go, cmd/govim/signature_help.go
Add two new Highlight groups that are used to highlight the
experimental signature help popup. Both can be overridden by
adding custom highlights to vimrc, e.g.:
```
highlight GOVIMSignature ctermfg=red
highlight GOVIMSignatureParam cterm=NONE ctermfg=green
```
GOVIMSignature is applied to the entire popup, and
GOVIMSignatureParam to the active parameter as reported by gopls.
=> cmd/govim: add highlighting to signature help popup

cmd/govim/config/config.go, cmd/govim/fillstruct.go, cmd/govim/main.go, cmd/govim/testdata/scenario_default/fillstruct.txt
Adds a new command, "GOVIMFillStruct", that populate fields with zero
value in a struct using gopls new code action "Fill struct".
Currently it must be called on an empty struct with the cursor above the
right bracket '}', see golang/go#39506.
=> cmd/govim: add support for "fill struct" code action

cmd/govim/fillstruct.go, cmd/govim/testdata/scenario_default/fillstruct.txt
Gopls updated fillstruct to always report results for the entire current
line. If there are more than one struct to fill on the same line, govim
now supports handling all edits sent by gopls.
=> cmd/govim: support multiple fillstruct edits

cmd/govim/gopls.go
In the near future, the default zero-command-implied serve behaviour
will disappear.
=> cmd/govim: use gopls serve command explicitly

cmd/govim/gopls.go
Reverts govim/govim#898.
From https://github.com/govim/govim/pull/898#issuecomment-653936668:
> We do run into some issues with our GOVIM_GOPLS_FLAGS env var that I, for example, use to set -remote=auto (and -ocagent). Since these two flags aren't a part of serve, gopls fails to start.
> I suggest that we revert this one until we have a nice solution for passing flags to gopls, unless the near future is too close :)
=> Revert "cmd/govim: use gopls serve command explicitly"

.github/workflows/vim_master.yml, internal/cmd/genconfig/genconfig.go
GitHub action actions/setup-go@v2 require passing "with.stable = false"
to use Go releases that aren't considered stable (such as beta
releases).
Without this the scheduled vim master tests will fail when using go 1.15
beta 1 for example.
=> ci: enable unstable (i.e. beta) go versions in vim master tests

autoload/govim/config.vim, cmd/govim/config/config.go, cmd/govim/config/gen_applygen.go, cmd/govim/gopls_client.go, cmd/govim/internal/vimconfig/vimconfig.go
As a part of gopls configuration the user can enable/disable specific
analyses.
A list of analyzers that can be enabled/disabled can be found in
[the gopls documentation](https://cs.opensource.google/go/tools/+/master:gopls/doc/analyzers.md) (note that the list isn't up to date):
Example:
`call govim#config#Set("Analyses", {"fillstruct": 1, "unreachable": 0})`
=> cmd/govim: add user enabled analyses configuration

cmd/govim/testdata/scenario_default/rename.txt
golang.org/issues/36743 has now been resolved. It appears therefore that
we can re-enable this part of the scenario_default/rename test.
=> cmd/govim: drop test skip based on golang.org/issues/36743

cmd/govim/testdata/scenario_default/quickfix_empty_files.txt, cmd/govim/testdata/scenario_tempmodfile/modfile_changes.txt
Disable tests that are flaky on CI as a result of intermittent gopls
bugs, namely golang.org/issues/39646 and golang.org/issues/40269.
We have open issues against these bugs, so it doesn't make sense to
suffer the daily disappointment of a failing build against gopls@master,
or indeed have a sometimes-red (and therefore misleading) main build.
=> cmd/govim: disable flaky quickfix_empty_files and modfile_changes tests

cmd/govim/code_lens.go, cmd/govim/config/config.go, cmd/govim/gopls_client.go, cmd/govim/main.go, cmd/govim/testdata/scenario_default/codelens_gc_details.txt
Add "Toggle gc annotation details" as new command, "GOVIMGCDetails".
The feature is toggled per package. When enabled, gopls will include
diagnostics of information severity with decisions about inlining,
escapes, etc.
Note that this is an experimental code lens feature in gopls that
might change or be removed.
=> cmd/govim: add "Toggle gc annotation details" feature

cmd/govim/testdata/scenario_default/quickfix_new_files.txt, go.mod, go.sum
Picks up fix for Go 1.16
Also includes a test fix for a change in error message introduced as
part of Go 1.16
=> deps: upgrade to github.com/rogpeppe/go-internal@v1.6.2

autoload/govim/config.vim, cmd/govim/config/config.go, cmd/govim/config/gen_applygen.go, cmd/govim/gopls.go, cmd/govim/gopls_client.go, cmd/govim/internal/types/popup.go, cmd/govim/internal/vimconfig/vimconfig.go, cmd/govim/main.go, cmd/govim/progress.go, cmd/govim/vimstate.go
Add experimental support for popups showing WorkDoneProgress.
The feature is disabled by default, and can be enabled via .vimrc:
`call govim#config#Set("ExperimentalProgressPopups", 1)`
When enabled govim will create notification style popups in
the upper right corner when gopls report progress of a task
(e.g. initial workspace load, running tests or "go generate").
The popup will close itself afterwards.
Note that this is an experimental feature. It has rather limited
use initially since govim doesn't yet support running tests via
gopls for example.
=> cmd/govim: add support for popups showing WorkDoneProgress

cmd/govim/testdata/scenario_default/quickfix_empty_files.txt
This reverts commit c8c4a6f83808a8b9fab26293c3ed508da6b39d77.
Reason: test is still flakey
=> Revert "cmd/govim: try to unskip tests skipped on golang.org/issues/39646

cmd/govim/testdata/scenario_bugs/bug_govim_940.txt, cmd/govim/textedit.go
Features that trigger applyProtocolTextEdits (such as organize imports
on save) didn't trigger an AST update. Calling functions that depend on
a fresh AST, like motion or signature help, could panic due to stale AST.
Fixes #940
=> cmd/govim: trigger AST parsing after applyProtocolTextEdits

cmd/govim/internal/golang_org_x_tools/lsp/cache/check.go, cmd/govim/internal/golang_org_x_tools/lsp/cache/load.go, cmd/govim/internal/golang_org_x_tools/lsp/cache/mod.go, cmd/govim/internal/golang_org_x_tools/lsp/cache/pkg.go, cmd/govim/internal/golang_org_x_tools/lsp/cache/session.go, cmd/govim/internal/golang_org_x_tools/lsp/cache/snapshot.go, cmd/govim/internal/golang_org_x_tools/lsp/cache/view.go, cmd/govim/internal/golang_org_x_tools/lsp/fake/editor.go, cmd/govim/internal/golang_org_x_tools/lsp/link.go, cmd/govim/internal/golang_org_x_tools/lsp/mod/diagnostics.go, cmd/govim/internal/golang_org_x_tools/lsp/source/hover.go, cmd/govim/internal/golang_org_x_tools/lsp/source/view.go, cmd/govim/internal/golang_org_x_tools/lsp/source/workspace_symbol.go, cmd/govim/internal/golang_org_x_tools/lsp/tests/tests.go, go.mod, go.sum
* internal/lsp/source: add some additional symbol downranking 6ec2cde9
* gopls/internal/regtest: remove ExpectNow e20053b7
* gopls/internal/regtest: simplify regtest EditorConfig 797bd0f0
* gopls/internal/regtest: add an InitialWorkspaceLoad expectation cbbbe623
* gopls/internal/regtest: move expectations to their own file bf5c620a
* internal/lsp: enable multi-module workspace mode by default in tests f4cefd1c
* internal/lsp/cache: fix -mod=mod for workspace module setups 2db8f0ff
=> deps: update x/tools and gopls to 6ec2cde9

cmd/govim/internal/golang_org_x_tools/imports/fix.go, cmd/govim/internal/golang_org_x_tools/lsp/cache/cache.go, cmd/govim/internal/golang_org_x_tools/lsp/cache/session.go, cmd/govim/internal/golang_org_x_tools/lsp/cache/snapshot.go, cmd/govim/internal/golang_org_x_tools/lsp/cache/view.go, cmd/govim/internal/golang_org_x_tools/lsp/cmd/cmd.go, cmd/govim/internal/golang_org_x_tools/lsp/completion.go, cmd/govim/internal/golang_org_x_tools/lsp/general.go, cmd/govim/internal/golang_org_x_tools/lsp/mod/code_lens.go, cmd/govim/internal/golang_org_x_tools/lsp/mod/hover.go, cmd/govim/internal/golang_org_x_tools/lsp/source/diagnostics.go, cmd/govim/internal/golang_org_x_tools/lsp/source/gc_annotations.go, cmd/govim/internal/golang_org_x_tools/lsp/source/hover.go, cmd/govim/internal/golang_org_x_tools/lsp/source/options.go, cmd/govim/internal/golang_org_x_tools/lsp/source/view.go, cmd/govim/internal/golang_org_x_tools/lsp/workspace.go, cmd/govim/internal/golang_org_x_tools/memoize/memoize.go, go.mod, go.sum
* internal/imports: don't set Context.WorkingDir, which was renamed 63098cc4
* internal/lsp: fix concurrency issues in view initialization 655488c8
* internal/lsp: pass options by reference instead of by value c537a342
* internal/lsp/cache: fix release tag parsing c9a70fc2
* internal/memoize: show key type in panics f128e626
* internal/lsp/mod: handle nil pointers in code lenses 587cf233
* cover: fix sorting of profile segment boundaries 56d9a0cd
* gopls/internal/regtest: simplify expectation return values c8d9e05b
=> deps: update x/tools and gopls to 63098cc4

autoload/govim/config.vim, cmd/govim/config/config.go, cmd/govim/config/gen_applygen.go, cmd/govim/gopls.go, cmd/govim/gopls_client.go, cmd/govim/internal/vimconfig/vimconfig.go, cmd/govim/main.go
These correspond to gopls configurations that can be set on the session.
=> cmd/govim/config: add SymbolMatcher and SymbolStyle config

cmd/govim/internal/golang_org_x_tools/imports/fix.go, cmd/govim/internal/golang_org_x_tools/lsp/cache/check.go, cmd/govim/internal/golang_org_x_tools/lsp/cache/load.go, cmd/govim/internal/golang_org_x_tools/lsp/cache/session.go, cmd/govim/internal/golang_org_x_tools/lsp/cache/snapshot.go, cmd/govim/internal/golang_org_x_tools/lsp/cache/view.go, cmd/govim/internal/golang_org_x_tools/lsp/command.go, cmd/govim/internal/golang_org_x_tools/lsp/fake/editor.go, cmd/govim/internal/golang_org_x_tools/lsp/fake/workdir.go, cmd/govim/internal/golang_org_x_tools/lsp/source/completion/completion.go, cmd/govim/internal/golang_org_x_tools/lsp/source/completion/completion_format.go, cmd/govim/internal/golang_org_x_tools/lsp/source/completion/completion_snippet.go, cmd/govim/internal/golang_org_x_tools/lsp/source/completion/deep_completion.go, cmd/govim/internal/golang_org_x_tools/lsp/source/view.go, go.mod, go.sum
* cmd/benchcmp: mention deprecation in docs d647fc25
* internal/lsp: handle modifications to the workspace module 78fed78f
* internal/lsp/source/completion: improve import suggestion labels e94ab728
* internal/lsp/cache: set GO111MODULE=auto in 1.16 d56e4e40
* all: fix tests in preparation for GO111MODULE=on by default 3791637d
* internal/lsp/source/completion: convert deep completion to bfs d148ae1e
* internal/imports: use ProcessEnv to filter files 0511c4cc
* gopls/internal/regtest: add expected ranges in completion tests 75ebdcb7
* internal/lsp: always show errors from running commands 60aba8ac
=> deps: update x/tools and gopls to d647fc25

cmd/govim/signature_help.go, cmd/govim/testdata/scenario_default/signature_help_anon.txt
This change enables experimental signature help for anonymous functions
such as:
```
go func() {
}()  // cursor inside ()
```
Fixes #957
=> cmd/govim: allow signature help for anonymous functions

cmd/govim/stringfns.go, cmd/govim/testdata/scenario_default/stringfn.txt
The line-wise mode always used two lines regardless of how many lines
that was selected. It is now possible to use GOVIMStringFn on more
lines.
=> cmd/govim: fix line-wise visual selection in GOVIMStingFn

cmd/govim/progress.go
Progress messages do sometimes contain newlines. To ensure that the
popup is rendered correct the progress message is now divided into
multiple lines.
=> cmd/govim: support multi-line progress messages in popup

cmd/govim/gopls_client.go, cmd/govim/testdata/scenario_default/show_message.txt
The other callbacks from gopls logs the entire param structure.
ShowMessage is updated to be consistent and do the same.
=> cmd/govim: Log ShowMessage callbacks in a consistent way

cmd/govim/gopls_client.go, cmd/govim/progress.go
Two small fixes for progress I caught while experimenting with "go
test":
- Multiple progress popups did overlap
- The progress message could intentionally start with space, we
shouldn't trim those
=> cmd/govim: fix overlap and formating issues in progress popups

cmd/govim/quickfix.go, cmd/govim/testdata/scenario_default/quickfix_fallback_directory.txt, cmd/govim/testdata/scenario_default/quickfix_fallback_last.txt, cmd/govim/testdata/scenario_default/quickfix_fallback_next.txt
GoVim often looses the selected qf entry, which results in setting qf index to 1.
This is especially annoying when you have a lot of warnings (from an other package opened in another buffer), and you try to fix compile errors. As soon as you fix the error, the qf list index becomes 1 and you have to scroll down the warnings to find again your compile errors.
Actually, the selected qf entry is kept only if you're not fixing it, or if your fix doesn't affect its line number.
I tried to patch this behavior a little bit, by selecting the closest entry with the same filename (or dirname), if the selected entry isn't found. Thus, the next qf index stays in the same file or package, so you can continue to fix compile errors. I tested a little bit and I found the behavior a way more convenient …
=> cmd/govim: improve qf index selection on update

cmd/govim/hover.go, cmd/govim/vimstate.go
This change renames the field "popupWinId" in vimstate to "popupWinID"
to avoid getting diagnostics about it when running with staticcheck
enabled.
=> cmd/govim: rename "vimstate.popupWinId" to please staticcheck

cmd/govim/child.go, cmd/govim/config/config.go, cmd/govim/cpprotocol.go, cmd/govim/flag.go, cmd/govim/main.go, cmd/govim/parent.go, cmd/govim/util.go
This enables govim to be used with fzf and other such Vim plugins that
require a client program in order to run a command. In the case of fzf,
the client instance of govim is used in order to re-query the parent
instance, which in turn calls on to gopls' workspace symbol search. This
allows the search results within fzf to be refined on each key stroke.
This approach, however, is not specific to fzf. Hence some configuration
of Vim/fzf is required. For a sample .vimrc configuration see:
https://github.com/govim/govim/wiki/vimrc-tips#-tip-use-fzf-with-workspace-symbol-search
Fixes #795
=> cmd/govim: first cut of command-line mode to query "parent"

_scripts/common.bash, _scripts/postRun.sh
Per https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands/
=> ci: drop use of set-env and add-path

cmd/govim/internal/golang_org_x_tools/gocommand/invoke.go, cmd/govim/internal/golang_org_x_tools/lsp/cache/view.go, cmd/govim/internal/golang_org_x_tools/lsp/command.go, cmd/govim/internal/golang_org_x_tools/lsp/debug/info.go, cmd/govim/internal/golang_org_x_tools/lsp/debug/serve.go, cmd/govim/internal/golang_org_x_tools/lsp/diagnostics.go, cmd/govim/internal/golang_org_x_tools/lsp/general.go, cmd/govim/internal/golang_org_x_tools/lsp/link.go, cmd/govim/internal/golang_org_x_tools/lsp/mod/hover.go, cmd/govim/internal/golang_org_x_tools/lsp/server.go, cmd/govim/internal/golang_org_x_tools/lsp/source/completion/completion.go, cmd/govim/internal/golang_org_x_tools/lsp/source/completion/deep_completion.go, cmd/govim/internal/golang_org_x_tools/lsp/source/format.go, cmd/govim/internal/golang_org_x_tools/lsp/source/hover.go, cmd/govim/internal/golang_org_x_tools/lsp/source/util.go, cmd/govim/internal/golang_org_x_tools/lsp/workspace.go, cmd/govim/testdata/scenario_default/quickfix_new_files.txt, go.mod, go.sum
* internal/lsp: fix end positions for multi-line comments with CRLF lines 598b068a
* internal/lsp: use a marker test for struct field ranking test bd56c0ad
* internal/lsp: order struct fields completions by definition 74a3905d
* gopls/internal/regtest: eliminate log duplication f544f6cb
* Revert "internal/lsp: explicitly watch all known directories" 9036a0f9
* internal/lsp: explicitly watch all known directories 3c3a8120
* internal/lsp: show critical error pop-ups as progress reports 74f2986d
* go/packages: handle variation an an error message 1d699438
* internal/lsp: fix capability registration for semantic tokens 6f6c72ae
* internal/gocommand: improve debug string d68bbb54
* go/packages: start with empty environment 247bdb27
* internal/lsp: get debug pages limping along again 1a2739ce
* …
=> deps: update x/tools and gopls to 598b068a

.github/workflows/docker-based_tests.yml, .github/workflows/vim_main.yml, internal/cmd/genconfig/genconfig.go
To be defensive ahead of the upcoming switch of latest
=> ci: use explicit version of Ubuntu on GitHub actions for now

cmd/govim/code_action.go, cmd/govim/config/config.go, cmd/govim/internal/types/popup.go, cmd/govim/main.go, cmd/govim/progress.go, cmd/govim/stringfns.go, cmd/govim/util.go, cmd/govim/vimstate.go
Add command GOVIMGoTest that, via gopls, execute test and benchmark
functions.
It will execute the test func under the cursor, and also support
executing multiple test functions via visual mode or ranged command.
E.g.
Select range via visual mode and call `":'<,'>GOVIMGoTest"` to test all
functions that intersect with the selection.
`":%GOVIMGoTest"` tests the entire file
`":20,$GOVIMGoTest"` tests all functions from line 20 to the end
Also fixes a offset error when there are multiple progress popups open
at the same time.
Updates #441
=> cmd/govim: add support for testing via gopls GOVIMGoTest

autoload/govim/config.vim, cmd/govim/config/config.go, cmd/govim/config/gen_applygen.go, cmd/govim/internal/vimconfig/vimconfig.go, cmd/govim/main.go, cmd/govim/progress.go
When calling :GOVIMLastProgress govim creates a new vim buffer. This
change adds the possibility to change how the new buffer is opened.
It also changes the default from "e" to "below 10split".
Change by setting OpenLastProgressWith to a string value, e.g:
"" - Do not open the new buffer
"e" - Open in same window
"split" - Open in split window
"belowright 15vsplit" - Open in vertical split, right side, 15 columns
=> cmd/govim: add new config that changes how last progress is opened

cmd/govim/code_action.go, cmd/govim/config/config.go, cmd/govim/gopls_client.go, cmd/govim/internal/types/popup.go, cmd/govim/main.go, cmd/govim/progress.go
When running `:GOVIMGoTest` the popup dialog will be styled according to
two new highlight definitions:
```
GOVIMGoTestPass
GOVIMGoTestFail
```
If one or more test fail, the popup will turn red. If all tests pass it
will turn green.
Redefine a highlight in your .vimrc to override default colors, e.g.
white on red when test fail:
```
highlight GOVIMGoTestFail ctermfg=15 ctermbg=1
```
=> cmd/govim: add "go test" popup highlighting

autoload/govim/config.vim, cmd/govim/config/config.go, cmd/govim/config/gen_applygen.go, cmd/govim/gopls_client.go, cmd/govim/internal/vimconfig/vimconfig.go, cmd/govim/testdata/scenario_gofumpt/gofumpt.txt, cmd/govim/testdata/scenario_gofumpt/user_config.json
Gopls do support changing formatter to gofumpt but the setting wasn't
exposed by govim. This change adds a new config that can be enabled by
adding a line to your .vimrc:
```vim
call govim#config#Set("Gofumpt", 1)
```
Closes #1004
=> cmd/govim: add support for gofumpt as formatter

cmd/govim/internal/golang_org_x_tools/lsp/cache/mod_tidy.go, cmd/govim/internal/golang_org_x_tools/lsp/cache/workspace.go, cmd/govim/internal/golang_org_x_tools/lsp/cmd/test/definition.go, cmd/govim/internal/golang_org_x_tools/lsp/cmd/test/imports.go, cmd/govim/internal/golang_org_x_tools/lsp/cmd/test/suggested_fix.go, cmd/govim/internal/golang_org_x_tools/lsp/cmd/test/workspace_symbol.go, cmd/govim/internal/golang_org_x_tools/lsp/diagnostics.go, cmd/govim/internal/golang_org_x_tools/lsp/diff/diff.go, cmd/govim/internal/golang_org_x_tools/lsp/diff/difftest/difftest.go, cmd/govim/internal/golang_org_x_tools/lsp/diff/myers/diff.go, cmd/govim/internal/golang_org_x_tools/lsp/mod/format.go, cmd/govim/internal/golang_org_x_tools/lsp/source/code_lens.go, cmd/govim/internal/golang_org_x_tools/lsp/source/format.go, cmd/govim/internal/golang_org_x_tools/lsp/tests/tests.go, cmd/govim/internal/golang_org_x_tools/lsp/tests/util.go, go.mod, go.sum
* internal/lsp: don't show duplicate diagnostics for go.mod errors ae774e97
* internal/lsp/source: only show "run file benchmarks" if available 5b06639e
* gopls/internal/regtest: test metadata validation only on save for go.mod 11a5667e
* go/analysis/passes/fieldalignment: filter comments from suggested fix 5b43ef93
* gopls/internal/regtest: test that accepting fix removes diagnostics 4b31ac34
* internal/lsp, gopls: recover from go-diff panics 008e4774
* internal/lsp: add titles to `go mod tidy` and update go.sum fixes 48e5bd11
=> deps: update x/tools and gopls to ae774e97

autoload/govim/config.vim
As stated in godoc `FormatOnSave` accepts `goimports-gofmt` const. But this value has not been added to validation function thus after adding line to `vimrc`:
```
call govim#config#Set("FormatOnSave", "goimports-gofmt")
```
exception occures:
```
E605: Exception not caught: Tried to set invalid value for key FormatOnSave: must be one of: ['', 'gofmt', 'goimports']
```
This PR fixes above mentioned issue.
=> Support "goimports-gofmt" value for FormatOnSave

cmd/govim/hover.go, cmd/govim/testdata/scenario_bugs/bug_govim_1013.txt
Setting either ExperimentalCursorTriggeredHoverPopupOptions or
ExperimentalMouseTriggeredHoverPopupOptions fields "col" or "line"
did result in a panic.
The value was parsed as a raw json message, but since it is already
parsed once before it paniced. We now type assert the value instead.
Updates #1012
=> cmd/govim: fix panic when using custom hover opts "col" / "line"

cmd/govim/internal/golang_org_x_tools/lsp/cache/load.go, cmd/govim/internal/golang_org_x_tools/lsp/cache/snapshot.go, cmd/govim/internal/golang_org_x_tools/lsp/cmd/call_hierarchy.go, cmd/govim/internal/golang_org_x_tools/lsp/cmd/check.go, cmd/govim/internal/golang_org_x_tools/lsp/cmd/highlight.go, cmd/govim/internal/golang_org_x_tools/lsp/cmd/implementation.go, cmd/govim/internal/golang_org_x_tools/lsp/cmd/prepare_rename.go, cmd/govim/internal/golang_org_x_tools/lsp/cmd/semantictokens.go, cmd/govim/internal/golang_org_x_tools/lsp/cmd/signature.go, cmd/govim/internal/golang_org_x_tools/lsp/debug/serve.go, cmd/govim/internal/golang_org_x_tools/lsp/diagnostics.go, cmd/govim/internal/golang_org_x_tools/lsp/fake/editor.go, cmd/govim/internal/golang_org_x_tools/lsp/fake/workdir.go, cmd/govim/internal/golang_org_x_tools/lsp/lsprpc/lsprpc.go, cmd/govim/internal/golang_org_x_tools/lsp/rename.go, cmd/govim/internal/golang_org_x_tools/lsp/source/rename.go, go.mod, go.sum
* gopls/internal/regtest: split regtests up into multiple packages db4c57db
* internal/lsp/cache: lock in snapshot.knownFilesInDir f871472f
* internal/lsp/source: make it an error to rename embedded fields c2bea79d
* gopls/internal/hooks: improve license file test 514964b7
* internal/lsp/cmd: improve help output of gopls subcommands 68bf78a6
* go/analysis/passes/fieldalignment: delete doc style comments in fix 4922717d
* gopls/internal/regtest: automate counting of editor notifications to await 917f61df
* internal/lsp: correct links provided in critical error pop-ups 2972602e
* internal/lsp: display current diagnostics in the debug server e13398c8
* gopls: factor out advanced documentation from the README cf1022a4
* gopls: mention workspaces and build systems in the README 87bc10f2
* …
=> deps: update x/tools and gopls to db4c57db

cmd/govim/motions.go, cmd/govim/testdata/scenario_default/motion.txt
This allows CTRL-O to return the cursor to position at which the
GOVIMMotion call was made. CTRL-I then returns you to that same "call
site".
With thanks to @roy2220 for raising the initial issue and proposing a
fix.
Fixes #931
=> cmd/govim: remember previous position before GOVIMMotion call

autoload/govim/config.vim, cmd/govim/config/config.go, cmd/govim/config/gen_applygen.go, cmd/govim/gopls.go, cmd/govim/internal/vimconfig/vimconfig.go, cmd/govim/main.go, cmd/govim/testdata/scenario_modreadonly/user_config.json
ExperimentalAllowModfileModifications controls whether gopls should
automatically modify go.{mod,sum} as a side effect of its use of cmd/go
or not. Setting this option to true can be considered a gopls equivalent
to setting GOFLAGS=-mod=mod when using cmd/go. Leaving it unset or
setting it to false is equivalent to -mod=readonly. Indeed setting
GOFLAGS=-mod=XYZ is now considered deprecated as a means of controlling
this behaviour in gopls.
For reference: in Go 1.16 cmd/go build commands default to -mod=readonly
(equivalent to leaving this option unset, or setting it to false),
whereas prior to Go 1.16 the default was -mod=mod (equivalent to setting
this option to true).
golang.org/issue/44008 tracks confirmation that this gopls option will
not be removed until a better alternative is …
=> cmd/govim: add ExperimentalAllowModfileModifications

cmd/govim/testdata/scenario_default/complete_module_cache.txt, cmd/govim/testdata/scenario_default/go_to_def_module_cache.txt, cmd/govim/testdata/scenario_default/go_to_def_newtab.txt, cmd/govim/testdata/scenario_default/go_to_def_split.txt, cmd/govim/testdata/scenario_default/go_to_def_vsplit.txt
This ensures that go.{mod,sum} are tidy when gopls starts.
Adding an unimported completion test that verifies go.{mod,sum} are
changed when we add a non-std package is captured in #1029.
=> cmd/govim: populate go.sum files for tests that use non-std packages

cmd/govim/buffer_events.go, cmd/govim/main.go, cmd/govim/vimstate.go
Using `:vimgrep` could result in a lot of short-lived buffers that is
sent to gopls since each file searched will trigger `BufReadPost`
autocommands.
Use `QuickFixCmdPre` & `QuickFixCmdPost` to detect when vimgrep runs,
and only add new buffers that still exists when vimgrep is done.
(see https://groups.google.com/g/vim_dev/c/qpu2O8cvprY/m/ZGAaOOlJBAAJ
for additional context)
Updates #1028
=> cmd/govim: do not add short-lived buffers during :vimgrep

cmd/govim/rename.go
Issue #1017 turns out to be caused by getbufinfo() returning a value
where at some level a field maps to a function. This cannot be JSON
encoded, obviously. The rather broad error message is fixed in:
https://github.com/vim/vim/commit/a853089479b60b829bab1c4a0a737a073415f8a7
Thanks to @LemonBoy for the excellent analysis in vim/vim#7802.
Fix this by being more specific in our call to getbufinfo. We only need
specific keys, so we should only fetch those.
Fixes #1017
=> cmd/govim: be more specific in our call to getbufinfo

cmd/govim/testdata/scenario_default/quickfix_empty_files.txt
As golang/go#39646 is closed we now re-enable the skipped test.
=> test: re-enable quickfix_empty_files test

cmd/govim/internal/golang_org_x_tools/lsp/cache/session.go, cmd/govim/internal/golang_org_x_tools/lsp/cache/snapshot.go, cmd/govim/internal/golang_org_x_tools/lsp/cache/view.go, cmd/govim/internal/golang_org_x_tools/lsp/command.go, cmd/govim/internal/golang_org_x_tools/lsp/command/command_gen.go, cmd/govim/internal/golang_org_x_tools/lsp/command/generate/generate.go, cmd/govim/internal/golang_org_x_tools/lsp/command/interface.go, cmd/govim/internal/golang_org_x_tools/lsp/fake/client.go, cmd/govim/internal/golang_org_x_tools/lsp/source/api_json.go, cmd/govim/internal/golang_org_x_tools/lsp/source/view.go, go.mod, go.sum
* go/analysis: extend the loopclosure checker to considering errgroup.Group.Go. 68c7d11a
* internal/lsp: always return file handles for nonexistent files add869b6
* internal/lsp/cache: build the workspace module deterministically 701d1429
* gopls/internal/regtest: exit if small machine ed2b1e9f
* godoc: convert Markdown files to HTML during serving 5bd3da9b
* gopls/internal/regtest: skip known flake TestGCDetails 9eba6e15
* gopls/internal/regtest/workspace: disable flaky MultiModule_OneBrokenModule test 9f3e2260
* internal/lsp: apply go.mod/sum changes via workspace edits 706a59cb
* internal/lsp/command: stub out the ListKnownPackages and AddImport commands 8316e564
=> deps: update x/tools and gopls to 68c7d11a

plugin/govim.vim
This feels like the right thing to do, and indeed in practice it's a
problem if we don't do this.
Tested by hand locally, because writing a test for this might well be
impossible given the infrastructure we have.
Fixes #1044
=> cmd/govim: set the user to not be busy when window focus is lost

cmd/govim/internal/golang_org_x_tools/lsp/cache/mod.go, cmd/govim/internal/golang_org_x_tools/lsp/cache/mod_tidy.go, cmd/govim/internal/golang_org_x_tools/lsp/cache/snapshot.go, cmd/govim/internal/golang_org_x_tools/lsp/cache/view.go, cmd/govim/internal/golang_org_x_tools/lsp/command.go, cmd/govim/internal/golang_org_x_tools/lsp/command/gen/gen.go, cmd/govim/internal/golang_org_x_tools/lsp/definition.go, cmd/govim/internal/golang_org_x_tools/lsp/fake/editor.go, cmd/govim/internal/golang_org_x_tools/lsp/source/hover.go, cmd/govim/internal/golang_org_x_tools/lsp/source/identifier.go, cmd/govim/internal/golang_org_x_tools/typesinternal/errorcode.go, cmd/govim/internal/golang_org_x_tools/typesinternal/errorcode_string.go, go.mod, go.sum
* txtar: minor fix in unit test input 4b197900
* internal/lsp: 'go get' packages instead of modules 9eb35354
* go/internal/cgo: set pkgdir with -srcdir instead of CWD 67e49ef2
* go/analysis/unitchecker: tell the user how to list the flags and analyzers 19ff21fb
* internal/lsp/command: rename package generate to gen d5b83329
* go/internal/gcimporter: reference golang/go#44339 in TODO 4534fc34
* go/internal/gcimporter: fix tests on darwin 35839b70
* go/internal/gcimporter: add "bundled" export data formats a1db63cc
* go/internal/gcimporter: fix reexporting compiler data b79f76fe
* go/internal/gcimporter: refactor IExportData tests 7fde01ff
* go/internal/gcimporter: simplify IExportData API 6055ccf0
* internal/lsp: refactor go command error handling 1e7abacf
* internal/lsp: fix nil pointer …
=> deps: update x/tools and gopls to 4b197900

_scripts/dockerRun.sh, _scripts/revendorToolsInternal.sh, cmd/govim/internal/golang_org_x_tools/lsp/source/completion/completion.go, go.mod, go.sum
Also includes some fixes for our CI build to work around
golang.org/issue/40067
* internal/lsp/source: filter out comparable from completion results f3748ed8
* go/analysis/passes/buildtag: update check for //go:build f47cb783
* go/loader: fix race 06713c25
* internal/regtest: fix regtests for the dev.typeparams Go branch 1f00549a
* txtar: minor fix in unit test input 4b197900
* internal/lsp: 'go get' packages instead of modules 9eb35354
* go/internal/cgo: set pkgdir with -srcdir instead of CWD 67e49ef2
* go/analysis/unitchecker: tell the user how to list the flags and analyzers 19ff21fb
* internal/lsp/command: rename package generate to gen d5b83329
* go/internal/gcimporter: reference golang/go#44339 in TODO 4534fc34
* go/internal/gcimporter: fix tests on darwin 35839b70
* …
=> deps: update x/tools and gopls to f3748ed8

cmd/govim/main.go, cmd/govim/suggested_fixes.go, cmd/govim/testdata/mod/example.com_withdeps_v1.0.0.txt, cmd/govim/testdata/scenario_tempmodfile/suggested_fix_go_get_package.txt, cmd/govim/testdata/scenario_tempmodfile/suggested_fix_remove_dep.txt, cmd/govim/testdata/scenario_tempmodfile/user_config.json, cmd/govim/vimstate.go
Code action responses can contain both WorkspaceEdit and Command
according to LSP 3.16, and edits should be applied before executing
the command.
We ignored the command field when handling suggested fixes. If a
suggested fix includes a command it is now executed after any edits are
applied.
Closes #1025
=> cmd/govim: support quickfix code actions returning commands

cmd/govim/internal/golang_org_x_tools/lsp/cache/analysis.go, cmd/govim/internal/golang_org_x_tools/lsp/cache/check.go, cmd/govim/internal/golang_org_x_tools/lsp/cache/errors.go, cmd/govim/internal/golang_org_x_tools/lsp/cache/load.go, cmd/govim/internal/golang_org_x_tools/lsp/cache/parse.go, cmd/govim/internal/golang_org_x_tools/lsp/cache/pkg.go, cmd/govim/internal/golang_org_x_tools/lsp/cache/snapshot.go, cmd/govim/internal/golang_org_x_tools/lsp/cmd/cmd.go, cmd/govim/internal/golang_org_x_tools/lsp/code_action.go, cmd/govim/internal/golang_org_x_tools/lsp/command.go, cmd/govim/internal/golang_org_x_tools/lsp/diagnostics.go, cmd/govim/internal/golang_org_x_tools/lsp/mod/diagnostics.go, cmd/govim/internal/golang_org_x_tools/lsp/server.go, cmd/govim/internal/golang_org_x_tools/lsp/source/diagnostics.go, cmd/govim/internal/golang_org_x_tools/lsp/source/gc_annotations.go, cmd/govim/internal/golang_org_x_tools/lsp/source/hover.go, cmd/govim/internal/golang_org_x_tools/lsp/source/options.go, cmd/govim/internal/golang_org_x_tools/lsp/source/rename_check.go, cmd/govim/internal/golang_org_x_tools/lsp/source/view.go, cmd/govim/internal/golang_org_x_tools/span/parse.go, cmd/govim/testdata/scenario_default/watcher.txt, go.mod, go.sum
Includes a small fix up for a diagnostic error message to match the new
expected value from gopls.
* internal/lsp: use pre-existing quick fixes for analysis diagnostics 376db572
* internal/lsp: run type error analyzers as part of diagnostics 144d5ced
* internal/lsp/source: eliminate GetTypeCheckDiagnostics 24439e3c
* internal/lsp: show human-readable const time.Duration as a comment dafbee50
* internal/lsp/cache: don't rely on related diagnostics if unsupported 9c452d85
* internal/lsp: key GC details off package ID 2ac05c83
* gopls/internal/hooks: compile URL regexp once 303d8bbb
* internal/lsp/cache: show type errors on parse errors in other files 94327d32
* gopls/internal/regtest: add a failing test for issue 44736 16b2c870
* internal/lsp/cache: split up sourceDiagnostics 78002535
* …
=> deps: update x/tools and gopls to 376db572

cmd/govim/buffer_events.go, cmd/govim/diagnostics.go, cmd/govim/implements.go, cmd/govim/main.go, cmd/govim/quickfix.go, cmd/govim/references.go, cmd/govim/testdata/scenario_default/quickfix_from_other.txt, cmd/govim/vimstate.go
QuickfixDiagnostics routine updates the quickfix list each time it
receives new diagnostics from gopls. This can be problematic if the
quickfix list has been populated by an other plugin, because the user
could be using this plugin.
The fix uses the quickfix title to determine if the quickfix is "owned"
by govim or by an other plugin. If the quicfix title is empty (which
means the quickfix has never been used before) or equal to "govim", then
govim considers it can change it, else it considers it cannot.
This condition is ignored when :GOVIMQuickfixDiagnostics is invoked by
the user, making possible for the user to display again the diagnostics
when he wants to.
=> cmd/govim: check quickfix list origin before update

.gitattributes
Per https://github.com/github/linguist/issues/5288 we were not using the
recursive form of a pattern to specify that everything under
cmd/govim/internal/golang_org_x_tools should be considered generated.
=> general: fix gitattributes

cmd/govim/gopls.go
If we are using module mode but isn't inside a module "go env GOMOD"
will return os.DevNull (e.g. /dev/null in linux).
That did incorrectly add a file watcher to /dev since govim thought
/dev/null was the go.mod file.
Now we skip creating a fs watcher if we can't find the module root.
Fixes #1067
=> cmd/govim: do not watch file system when there is no module root

cmd/govim/gopls.go, cmd/govim/main.go, plugin/govim.vim
This change adds the possibility to set multiple values when using
`GOVIM_LOG`. It is mainly a preparation for the upcoming file watcher
refactoring where the intention is to add opt-in for more verbose
logging.
=> cmd/govim: extend GOVIM_LOG to accept multiple commaseparated values

cmd/govim/internal/golang_org_x_tools/event/label/label.go, cmd/govim/internal/golang_org_x_tools/jsonrpc2_v2/jsonrpc2.go, cmd/govim/internal/golang_org_x_tools/jsonrpc2_v2/serve.go, cmd/govim/internal/golang_org_x_tools/lsp/cache/check.go, cmd/govim/internal/golang_org_x_tools/lsp/cache/mod_tidy.go, cmd/govim/internal/golang_org_x_tools/lsp/cache/snapshot.go, cmd/govim/internal/golang_org_x_tools/lsp/cache/view.go, cmd/govim/internal/golang_org_x_tools/lsp/fake/editor.go, cmd/govim/internal/golang_org_x_tools/lsp/protocol/typescript/README.md, cmd/govim/internal/golang_org_x_tools/lsp/protocol/typescript/code.ts, cmd/govim/internal/golang_org_x_tools/lsp/protocol/typescript/tsconfig.json, cmd/govim/internal/golang_org_x_tools/lsp/protocol/typescript/util.ts, cmd/govim/internal/golang_org_x_tools/lsp/semantic.go, cmd/govim/internal/golang_org_x_tools/lsp/snippet/snippet_builder.go, cmd/govim/internal/golang_org_x_tools/lsp/source/api_json.go, cmd/govim/internal/golang_org_x_tools/lsp/source/completion/completion.go, cmd/govim/internal/golang_org_x_tools/lsp/source/completion/format.go, cmd/govim/internal/golang_org_x_tools/lsp/source/completion/literal.go, cmd/govim/internal/golang_org_x_tools/lsp/source/completion/postfix_snippets.go, cmd/govim/internal/golang_org_x_tools/lsp/source/completion/util.go, cmd/govim/internal/golang_org_x_tools/lsp/source/extract.go, cmd/govim/internal/golang_org_x_tools/lsp/source/hover.go, cmd/govim/internal/golang_org_x_tools/lsp/source/identifier.go, cmd/govim/internal/golang_org_x_tools/lsp/source/options.go, cmd/govim/internal/golang_org_x_tools/lsp/source/signature_help.go, cmd/govim/internal/golang_org_x_tools/lsp/tests/README.md, go.mod, go.sum
* internal/lsp/cache: fix race condition in snapshot's initializedErr 8c34cc9c
* gopls/internal/regtest: re-enable the gc_details regtest for -short 0deaffd2
* internal/lsp/source: respond with the underlying type to Type Definition requests for composite types af364066
* godoc/static: link to golang.org for content moved out of Go root 682c7e60
* internal/lsp/semantic: fix some type definitions ca627f83
* internal/lsp/protocol/typescript: small cleanups and add tsconfig.json 04595890
* internal/jsonrpc2_v2: move the idle timeout handling out of the server b0e994dc
* internal/lsp: remove unnecessary call to WorkspacePackages in mod tidy 95535753
* internal/lsp/source: fix docs for fields of anonymous structs/interfaces 769264cf
* internal/lsp/source: skip blank identifiers during the …
=> deps: update x/tools and gopls to 8c34cc9c

cmd/govim/gopls.go
Workaround golang/go#45377 by having gopls log to os.DevNull in case we
don't need gopls logging from a govim perspective.
=> cmd/govim: workaround golang/go#45377

autoload/govim/config.vim, cmd/govim/config/config.go, cmd/govim/config/gen_applygen.go, cmd/govim/gopls_client.go, cmd/govim/internal/vimconfig/vimconfig.go, cmd/govim/testdata/scenario_directoryfilter/directory_filter.txt, cmd/govim/testdata/scenario_directoryfilter/user_config.json
`gopls` has an option to [`DirectoryFilters`](https://github.com/golang/tools/blob/e9a2c0706a5b9cc8ee5965d5a50c996ffb255a7b/internal/lsp/source/options.go#L213). It allows to add or remove certain directories from workspace. This option is especially useful if workspace is a root of giant monorepository project. Without this option it is impossible to open such projects due to endless indexing process.
This PR adds support for this option via standard `govim` config option.
=> Support DirectoryFilters config option for gopls

cmd/govim/internal/golang_org_x_tools/lsp/cache/snapshot.go, cmd/govim/internal/golang_org_x_tools/lsp/fake/editor.go, cmd/govim/internal/golang_org_x_tools/lsp/mod/code_lens.go, cmd/govim/internal/golang_org_x_tools/lsp/source/api_json.go, cmd/govim/internal/golang_org_x_tools/lsp/source/highlight.go, cmd/govim/internal/golang_org_x_tools/lsp/source/options.go, go.mod, go.sum
* gopls/internal/coverage: apply gofmt to the build tag syntax 0243799c
* internal/lsp/source: small fixes to directory filters be791d07
* go/tools: add vet check for direct comparion of reflect.Values b261fe96
* internal/lsp: switch to 'go get -u ./...' for transitive upgrades e78b40c7
* gopls/internal/coverage: better error messages and output 3ac76b8b
* Revert "internal/lsp/cache: disable GOPACKAGESDRIVER" c6024661
* go/internal/gcimporter: ensure that imported floats are of float kind 35a91593
* go/internal/gcimporter: merge go1.11 tests back into gcimporter_test.go 5d334387
* internal/lsp/source: fix Highlight for std and 3rd-party packages 11c3f835
=> deps: update x/tools and gopls to 0243799c

cmd/govim/main.go
As explained in golang.org/issue/45476, all call to Shutdown does not
properly interrupt "work" that might be in progress in gopls. This has
the effect of blocking an exit from Vim.
Workaround this for now by limiting the wait time to 500ms, which is
effectively the measure of a user's patience before anger/frustration
sets in!
=> cmd/govim: do not wait more than 500ms for gopls Shutdown

cmd/govim/internal/fswatcher/fswatcher.go, cmd/govim/internal/fswatcher/os_darwin.go, cmd/govim/internal/fswatcher/os_others.go, cmd/govim/testdata/scenario_default/watcher.txt, cmd/govim/testdata/scenario_default/watcher_go_rules.txt, cmd/govim/watcher.go
The previous file watchers was broken in several ways, where the two
major was:
* A race condition in the non-darwin watcher (#492)
* Darwin recursively watched the entire module directory, disregarding
sub-modules, testdata directories and directories prefixed by _ or .
This caused the test suite to always fail on macOS.
This change:
* Moves the non-recursive handling into os_other.go
* Adds an OS independent function that filter events specifically
disallowed by Go (i.e. "testdata", sub-modules and directories
prefixed by _ or .
* Adds more tests to raise file watching cover
Closes #492
=> cmd/govim: refactor file watching

cmd/govim/internal/golang_org_x_tools/jsonrpc2_v2/jsonrpc2.go, cmd/govim/internal/golang_org_x_tools/jsonrpc2_v2/serve.go, cmd/govim/internal/golang_org_x_tools/lsp/general.go, cmd/govim/internal/golang_org_x_tools/lsp/lsprpc/binder.go, cmd/govim/internal/golang_org_x_tools/lsp/lsprpc/lsprpc.go, cmd/govim/internal/golang_org_x_tools/lsp/protocol/protocol.go, cmd/govim/internal/golang_org_x_tools/lsp/protocol/tsclient.go, cmd/govim/internal/golang_org_x_tools/lsp/protocol/tsprotocol.go, cmd/govim/internal/golang_org_x_tools/lsp/protocol/tsserver.go, cmd/govim/internal/golang_org_x_tools/lsp/protocol/typescript/code.ts, cmd/govim/internal/golang_org_x_tools/lsp/server.go, cmd/govim/internal/golang_org_x_tools/lsp/source/completion/format.go, cmd/govim/internal/golang_org_x_tools/lsp/source/hover.go, cmd/govim/internal/golang_org_x_tools/lsp/source/identifier.go, cmd/govim/internal/golang_org_x_tools/lsp/source/references.go, cmd/govim/internal/golang_org_x_tools/lsp/source/signature_help.go, cmd/govim/internal/golang_org_x_tools/lsp/workspace.go, go.mod, go.sum
* internal/lsp: report used semantic token order in registerCapability 49064d23
* internal/lsp/lsprpc: implement cancellation using jsonrpc2_v2 a0f4b7b8
* internal/lsp/lsprpc: partial integration of the jsonrpc_v2 library f451690e
* internal/jsonrpc2_v2: consider ErrClosedPipe as a closing error 17b34666
* internal/lsp/source: re-parse if needed when collecting identifier info 6da3d7ac
=> deps: update x/tools & gopls to 49064d2

cmd/govim/config/config.go
The link to gopls documentation describing analyzers was broken. It now
points to the correct page.
=> cmd/govim: update reference to gopls analyzer documentation in config.go

cmd/govim/internal/golang_org_x_tools/gocommand/version.go, cmd/govim/internal/golang_org_x_tools/jsonrpc2_v2/serve.go, cmd/govim/internal/golang_org_x_tools/lsp/cache/check.go, cmd/govim/internal/golang_org_x_tools/lsp/cache/load.go, cmd/govim/internal/golang_org_x_tools/lsp/cache/parse.go, cmd/govim/internal/golang_org_x_tools/lsp/cache/session.go, cmd/govim/internal/golang_org_x_tools/lsp/cache/snapshot.go, cmd/govim/internal/golang_org_x_tools/lsp/cache/view.go, cmd/govim/internal/golang_org_x_tools/lsp/fake/edit.go, cmd/govim/internal/golang_org_x_tools/lsp/fake/editor.go, cmd/govim/internal/golang_org_x_tools/lsp/fake/workdir.go, cmd/govim/internal/golang_org_x_tools/lsp/regtest/expectation.go, cmd/govim/internal/golang_org_x_tools/lsp/regtest/runner.go, cmd/govim/internal/golang_org_x_tools/lsp/source/api_json.go, cmd/govim/internal/golang_org_x_tools/lsp/source/call_hierarchy.go, cmd/govim/internal/golang_org_x_tools/lsp/source/completion/completion.go, cmd/govim/internal/golang_org_x_tools/lsp/source/completion/literal.go, cmd/govim/internal/golang_org_x_tools/lsp/source/format.go, cmd/govim/internal/golang_org_x_tools/lsp/source/options.go, cmd/govim/internal/golang_org_x_tools/lsp/source/types_format.go, cmd/govim/internal/golang_org_x_tools/lsp/template/parse.go, cmd/govim/internal/golang_org_x_tools/testenv/testenv.go, go.mod, go.sum
* internal/lsp: memoize allKnownSubdirs instead of recomputing 1225b6f5
* lsp/completion: don't offer untyped conversions 7295a4e7
* vta: adds VTA graph construction for basic program statements bf132055
* gopls/internal/regtest: clean up TestFillReturnsPanic 8f2cf6cc
* internal/lsp: handle empty buffers in template parsing 4abb1e2f
* internal/lsp: don't diagnose/analyze intermediate test variants 7ac129f2
* internal/lsp: address some staticcheck warning 1c2154ae
* Revert "internal/lsp/cache: don't delete metadata until it's reloaded" 384c3925
* internal/testenv: treat netbsd-arm*-bsiegert as slow builders 29f5b8f0
* go/packages/packagestest: make Export skip tests involving unsupported links 79224910
* Revert "internal/lsp: enable semantic tokens by default" 726034ec
* …
=> deps: update x/tools & gopls to 1225b6f5

cmd/govim/go_to_def.go, cmd/govim/rename.go, cmd/govim/testdata/mod/example.com_bla!h_v1.0.0.txt, cmd/govim/testdata/scenario_default/go_to_def_upper_case.txt
When interpretting URIs from gopls, we need to use the
span.URI.Filename() when we are expecting a filename. This ensures we
properly decode the URL, which in turn properly decodes the hex-encoded
path elements, like '!', which can appear in module paths.
=> cmd/govim: use span.URI.Filename() when handling filenames

cmd/govim/testdata/scenario_default/diagnostic_highlights.txt, cmd/govim/testdata/scenario_default/reference_highlight.txt
From the corresponding commit message in Vim:
patch 8.2.3233: prop_list() and prop_find() do not indicate the buffer
Problem:    prop_list() and prop_find() do not indicate the buffer for the
used type.
Solution:   Add "type_bufnr" to the results.
As a result, we need to amend some of our golden files.
See https://github.com/cue-lang/cue/issues/822#issuecomment-889927503
for a discussion on how we could potentially make our lives simpler
using CUE.
=> cmd/govim: adapt to Vim v8.2.3233 changes

cmd/govim/internal/golang_org_x_tools/lsp/cache/parse.go, cmd/govim/internal/golang_org_x_tools/lsp/cache/snapshot.go, cmd/govim/internal/golang_org_x_tools/lsp/semantic.go, cmd/govim/internal/golang_org_x_tools/lsp/source/extract.go, cmd/govim/internal/golang_org_x_tools/lsp/source/fix.go, cmd/govim/internal/golang_org_x_tools/lsp/source/implementation.go, cmd/govim/internal/golang_org_x_tools/lsp/source/util.go, cmd/govim/testdata/scenario_default/go_to_def_module_cache.txt, cmd/govim/testdata/scenario_default/go_to_def_std_lib.txt, cmd/govim/testdata/scenario_default/go_to_def_upper_case.txt, go.mod, go.sum
CL 338789 fixed a bug on the gopls side with respect to finding
references. This highlighted a couple of bad tests on the govim side: we
where trying to jump to definition with the cursor over the '.' in, say,
'time.Kitchen' - this is ambiguous at best.
Update to the latest tools/gopls and fix our test assertions in the
process, by adjusting the cursor position to the right by one.
* go/types/objectpath: minor doc fix 3395cb03
* internal/lsp: send "extract variable" edits ordered bb69444e
* internal/lsp: handle invalid positions in semantic token debug logic f8cfadac
* internal/lsp: remove duplicated loop that copies IDs 45eff0fd
* internal/lsp: find references for ident before selector a6684984
* go/ssa/interp: handle nil slice convert to array pointer 3810fa82
* go/pointer: fix …
=> deps: update x/tools and gopls to 3395cb03

cmd/govim/internal/golang_org_x_tools/lsp/cache/load.go, cmd/govim/internal/golang_org_x_tools/lsp/cache/os_darwin.go, cmd/govim/internal/golang_org_x_tools/lsp/cache/os_windows.go, cmd/govim/internal/golang_org_x_tools/lsp/cache/session.go, cmd/govim/internal/golang_org_x_tools/lsp/cache/snapshot.go, cmd/govim/internal/golang_org_x_tools/lsp/cache/symbols.go, cmd/govim/internal/golang_org_x_tools/lsp/cache/view.go, cmd/govim/internal/golang_org_x_tools/lsp/fuzzy/input.go, cmd/govim/internal/golang_org_x_tools/lsp/fuzzy/matcher.go, cmd/govim/internal/golang_org_x_tools/lsp/fuzzy/symbol.go, cmd/govim/internal/golang_org_x_tools/lsp/lsprpc/lsprpc.go, cmd/govim/internal/golang_org_x_tools/lsp/protocol/tsclient.go, cmd/govim/internal/golang_org_x_tools/lsp/protocol/tsprotocol.go, cmd/govim/internal/golang_org_x_tools/lsp/protocol/tsserver.go, cmd/govim/internal/golang_org_x_tools/lsp/protocol/typescript/util.ts, cmd/govim/internal/golang_org_x_tools/lsp/source/api_json.go, cmd/govim/internal/golang_org_x_tools/lsp/source/identifier.go, cmd/govim/internal/golang_org_x_tools/lsp/source/options.go, cmd/govim/internal/golang_org_x_tools/lsp/source/view.go, cmd/govim/internal/golang_org_x_tools/lsp/source/workspace_symbol.go, cmd/govim/internal/golang_org_x_tools/lsp/template/parse.go, cmd/govim/internal/golang_org_x_tools/span/uri.go, cmd/govim/internal/golang_org_x_tools/typeparams/common.go, cmd/govim/internal/golang_org_x_tools/typeparams/notypeparams.go, cmd/govim/internal/golang_org_x_tools/typeparams/typeparams.go, go.mod, go.sum
* internal/lsp/source: fix race in workspace symbols with multiple views 7bc3c281
* go/analysis/passes/asmdecl: support in-register result in ABIInternal 337cebd2
* internal/lsp/source: parallelize workspace symbols fcc905b2
* internal/lsp/source: don't build low scoring workspace symbols 28b26823
* internal/lsp/source: offer the fast fuzzy matcher as an option f35d7dcc
* internal/lsp/fuzzy: add a new fuzzy matcher optimized for Go symbols bfe69c31
* internal/lsp: update the fuzzy matcher to operate on chunks 15eebf7e
* internal/lsp/source: change symbol matcherFuncs to accept chunks 0d28b7d7
* internal/lsp: precompute workspace symbols 0f3931c7
* internal/lsp/source: use match indexes to compute dynamic symbols 48691842
* internal/lsp/cache: parse files with ParseFull mode to check if …
=> deps: update x/tools and gopls to 7bc3c281

plugin/govim.vim
Some flavors of "mktemp", at least macOS and possibly OpenBSD) require
that the template ends with X's (instead of just having them anywhere in
the template). On macOS they won't be converted to a random number at
all.
This change drops the .log extension from the vim channel log. We could
have run mktemp in "dry-run" mode to just generate a file name, but that
actually creates and removes the file on macOS. That introduces a race
that makes it fairly easy for other users on the same system to "hijack"
the logfile.
=> plugin/govim: drop .log suffix on vim channel log

cmd/govim/main_test.go, govim_test.go, testdriver/testdriver.go, testsetup/testsetup.go
When #1101 was merged I accidentally introduced a data race by modifying
the global VimCommand. We now make a local copy that is modified
instead.
Closes #1104
=> testdriver: fix data race introduced in #1101

cmd/govim/hover.go
Type parameter support in gotip has a few diagnostics that is
multi-lined. We now properly show them in hover popups as multiple
lines, and appends the source to the first line only.
=> cmd/govim: support multi-lined diagnostics in hover

autoload/govim/config.vim, cmd/govim/config/config.go, cmd/govim/config/gen_applygen.go, cmd/govim/gopls_client.go, cmd/govim/internal/vimconfig/vimconfig.go, cmd/govim/testdata/scenario_goplsmemmode_degradeclosed/rename.txt, cmd/govim/testdata/scenario_goplsmemmode_degradeclosed/user_config.json
In gopls there is an experimental feature that can be used to reduce the
memory footprint by degrade features in packages without any open files.
This can be useful in large single-moduled mono repos that otherwise
consume lots of resources.
We support the both modes defined in gopls, "Normal" and "DegradeClosed"
where "Normal" is the default behaviour. To use "DegradeClosed" add a
line to your .vimrc:
```
call govim#config#Set("ExperimentalGoplsMemoryMode","DegradeClosed")
```
=> cmd/govim: Support setting gopls memory mode

cmd/govim/gopls_server.go, cmd/govim/internal/golang_org_x_tools/lsp/analysis/fillreturns/fillreturns.go, cmd/govim/internal/golang_org_x_tools/lsp/analysis/infertypeargs/infertypeargs.go, cmd/govim/internal/golang_org_x_tools/lsp/cache/imports.go, cmd/govim/internal/golang_org_x_tools/lsp/cache/session.go, cmd/govim/internal/golang_org_x_tools/lsp/cache/view.go, cmd/govim/internal/golang_org_x_tools/lsp/protocol/tsclient.go, cmd/govim/internal/golang_org_x_tools/lsp/protocol/tsprotocol.go, cmd/govim/internal/golang_org_x_tools/lsp/protocol/tsserver.go, cmd/govim/internal/golang_org_x_tools/lsp/protocol/typescript/README.md, cmd/govim/internal/golang_org_x_tools/lsp/protocol/typescript/code.ts, cmd/govim/internal/golang_org_x_tools/lsp/protocol/typescript/util.ts, cmd/govim/internal/golang_org_x_tools/lsp/server_gen.go, cmd/govim/internal/golang_org_x_tools/lsp/source/api_json.go, cmd/govim/internal/golang_org_x_tools/lsp/template/completion.go, cmd/govim/internal/golang_org_x_tools/memoize/memoize.go, cmd/govim/internal/golang_org_x_tools/typeparams/normalize.go, cmd/govim/internal/golang_org_x_tools/typeparams/typeparams_go117.go, go.mod, go.sum
Note that this also contains updates to gopls_server.go to match latest
protocol changes.
* gopls/doc: fix rendering of example for the infertypeargs analyzer c882a49e
* internal/lsp/analysis/fillreturns: update fillreturns for new type errs f64c0f46
* internal/memoize: do not allow (*Generation).Acquire to fail e212aff8
* go/types/typeutil: add support for mapping generic types 2ac48c60
* go/internal/gcimporter: allow reusing empty interfaces on the RHS of type decls df48029e
* internal/lsp/protocol: fix whitespace in comments d99d6fae
* gopls/internal/regtest/misc: temporarily skip TestGenerateProgress 3c63f308
* internal/lsp/protocol: bring the LSP stubs up to date 615f9a6b
* refactor/importgraph: set env from packagestest.Export and check errors from Build 1fd30d29
* internal/memoize: …
=> deps: update x/tools and gopls to c882a49eac7c

cmd/govim/config/config.go, cmd/govim/main.go, cmd/govim/testdata/scenario_default/go_to_def_upper_case.txt
The previous default value for for the config setting
ExperimentalAllowModfileModifications was "true", which isn't the
default value for gopls.
Enabling this setting causes issues with the new workspace mode in
gopls as described in #1112 and referred golang/go#48186. It also seem
to cause issues in upcoming Go 1.18, see golang/go#51056.
Closes #1112
=> cmd/govim: disable allowModfileModifications by default

plugin/govim.vim
We now consider Go version in addition to govim commit when we determine
if govim and gopls should be reinstalled.
This helps when jumping between Go versions or following along with
an often updated gotip.
Fixes #1135
=> plugin: reinstall when Go version changes

cmd/govim/gopls.go, cmd/govim/main.go, cmd/govim/testdata/scenario_default/workspace_mode.txt, testdriver/testdriver.go
As per golang/go#50955 govim now uses the directory of GOWORK if set
before falling back to use the directory of GOMOD.
The added test also introduced a new testscript test feature, setting
which directory vim should start from.
=> cmd/govim: add support for go.work workspace

cmd/govim/progress.go, cmd/govim/suggested_fixes.go
As of vim v8.2.4260 global function callbacks now require to be prefixed
with "g:". If the callback function cannot be found vim will report an
error when the initial package load popup closes, something that
happened when using v8.2.4260+ and had ExperimentalProgressPopups
enabled.
=> cmd/govim: use "g:"-prefix for global callbacks and filter

cmd/govim/signature_help.go
There was a race where an user could trigger a signaturehelp call to
gopls before the buffer wasn't tracked by govim, for example by having
an autocommand for CursorHold.
This is now prevented by ignoring signature calls for buffers that isn't
tracked by govim.
=> cmd/govim: ignore signaturehelp requests for non-tracked buffers

cmd/govim/signature_help.go, cmd/govim/testdata/scenario_default/signature_typeparam.txt, go.mod, go.sum
Go 1.18 introduced two new ast nodes that our signature help didn't
recognize, which led to panics. Those have added along with a new test.
=> cmd/govim: add signaturehelp support for type parameters

cmd/govim/gopls.go
LSP 3.15.0 added support for sending information about the client as part of the InitializeParams message. This change will make govim send it's name and version as a part of that message to gopls.
Also see golang/go#61038.
=> cmd/govim: populate clientinfo in initialize params sent to gopls

cmd/govim/internal/golang_org_x_tools/refactor/inline/callee.go, cmd/govim/internal/golang_org_x_tools/refactor/inline/inline.go, cmd/govim/internal/golang_org_x_tools_gopls/lsp/source/embeddirective.go, cmd/govim/internal/golang_org_x_tools_gopls/lsp/source/hover.go, go.mod, go.sum
* internal/refactor/inline: consider "", 0.0, 1.0 duplicable 451716b51
* internal/refactor/inline: tweak everything test for cgo 792f91f70
* internal/refactor/inline: fix pkgname shadowing bug 941629930
* gopls/internal/lsp/fake: don't set a completion budget for tests 4cd12d6da
* gopls/internal/lsp: hover over embed directives 57ecf488e
* gopls/internal/lsp/cache: remove snapshot.typeCheckMu 6de34480a
* gopls/internal/regtest/source/completion: reuse functionCallSnippet in unimported completion 7f23bc81d
* gopls/internal/lsp: use matcher score in ranking unimported candidates 3d03fbd05
* gopls/internal/lsp/source: don't complete to golang.org/toolchain 7577387a8
=> deps: update x/tools and gopls to 451716b51

_scripts/dockerRun.sh, go.mod, govim.go, tools.go
Using the go run $pkg@$version to remove them from our deps list.
=> deps: use updated versions of staticcheck and stringer
